import { Unit } from "@/lib/types";

// Sample unit data for initial seeding — will be replaced by scrapers
export const SAMPLE_UNITS: Unit[] = [
  // ============================================================================
  // Colorado Elk
  // ============================================================================
  {
    id: "co-elk-011",
    stateId: "CO",
    speciesId: "elk",
    unitCode: "11",
    unitName: "White River",
    successRate: 0.22,
    trophyRating: 6,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 1,
    terrainType: ["Sagebrush", "Timber"],
    pressureLevel: "Moderate",
    elevationRange: [6500, 9500],
    publicLandPct: 0.45,
    tagQuotaNonresident: 150,
    notes: "High road density. 1st Rifle limited season. Good truck-based glassing.",
    nearestAirport: "DEN (3.5 hrs) or GJT (2 hrs)",
    driveTimeFromAirport: "3.5 hours from DEN via I-70 W → Hwy 13 N to Meeker",
    tacticalNotes: {
      accessMethod: "Truck-accessible. CR 5, 8, and 10 are the main forest roads. 4WD recommended after rain but AWD works in dry conditions. BLM and NF roads are well-maintained.",
      glassingStrategy: "Morning: glass south-facing sage parks from CR 5 overlooks at dawn. Evening: watch transition zones between sage flats and dark timber at 8,000-8,500 ft. Bulls bed in timber by 9am.",
      campingOptions: "Free dispersed camping on BLM and National Forest land. Popular camps off CR 5, along Piceance Creek, and at Flag Creek trailhead. Water from stock tanks or pack your own.",
      bestSeasonTier: "2nd Rifle / 3rd Rifle",
      bestArrivalDate: "Oct 20 for 2nd Rifle, Nov 3 for 3rd Rifle (mule deer rut)",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "260-300 class bulls. Solid quantity of satellite bulls in the 250 range. 3rd Rifle is prime for 150-170 class mule deer bucks.",
      waterSources: "Piceance Creek, stock tanks throughout, natural springs. GPS waypoints on onX Maps.",
      cellService: "Verizon spotty along CR 5 corridor. AT&T poor everywhere. Download offline maps and waypoints before leaving the highway.",
      proTip: "Glass the transition zones between sage flats and timber edges at dawn. Bulls move from feeding areas to bedding timber within the first hour of light. Work ridge-to-ridge with good glass — don't hike until you've located animals.",
    },
  },
  {
    id: "co-elk-211",
    stateId: "CO",
    speciesId: "elk",
    unitCode: "211",
    unitName: "Bear's Ears",
    successRate: 0.28,
    trophyRating: 7,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 2,
    terrainType: ["Sagebrush", "Mixed"],
    pressureLevel: "Moderate",
    elevationRange: [6000, 9000],
    publicLandPct: 0.45,
    tagQuotaNonresident: 100,
    notes: "Sweet spot for 1st Rifle elk. Animals in transition ranges near water.",
    nearestAirport: "DEN (3.5 hrs) or GJT (2.5 hrs)",
    driveTimeFromAirport: "3.5 hours from DEN via I-70 W → Hwy 13 N",
    tacticalNotes: {
      accessMethod: "Mix of truck-accessible roads and moderate hikes. Main access via CR 8 and BLM roads south of Meeker. 4WD required for most side roads.",
      glassingStrategy: "Focus on Bear's Ears ridgeline for morning glass sessions. Elk transition between sage parks and oak brush draws. Evening hunts along water sources (creek bottoms) produce consistent action.",
      campingOptions: "Dispersed camping along CR 8. Flat Tops Wilderness trailheads for backpack-in options. Several developed campgrounds in the area.",
      bestSeasonTier: "1st Rifle / 2nd Rifle",
      bestArrivalDate: "Oct 12 for 1st Rifle, Oct 20 for 2nd Rifle",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "Consistent 280-320 class bull opportunity. This is a step up from Unit 11 in quality. Mule deer also excellent — 150-170 class during 3rd Rifle rut.",
      waterSources: "White River, tributary creeks, stock tanks. Water sources are key to patterning animals in this unit.",
      cellService: "Similar to Unit 11 — limited. Plan accordingly.",
      proTip: "The transition zone between oak brush and sage at 7,500-8,000 ft is the sweet spot. Set up above these draws at first light and glass down. Bulls use the draws as travel corridors between feeding and bedding.",
    },
  },
  {
    id: "co-elk-004",
    stateId: "CO",
    speciesId: "elk",
    unitCode: "4",
    unitName: "Piceance Basin",
    successRate: 0.35,
    trophyRating: 5,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 0,
    terrainType: ["Mixed", "Timber"],
    pressureLevel: "Moderate",
    elevationRange: [6500, 10000],
    publicLandPct: 0.40,
    tagQuotaNonresident: 200,
    notes: "1st Rifle high success. Mixed timber/aspen/BLM.",
    nearestAirport: "DEN (4 hrs) or GJT (1.5 hrs)",
    driveTimeFromAirport: "4 hours from DEN, 1.5 hours from GJT via I-70",
    tacticalNotes: {
      accessMethod: "Good road access on BLM and NF roads. 2WD passable on main routes in dry conditions. Side roads require 4WD.",
      glassingStrategy: "Glass aspen benches at dawn. Elk congregate in the aspen-to-spruce transition during October. Look for fresh sign (rubs, wallows) in aspen draws.",
      campingOptions: "BLM dispersed camping plentiful. Several developed campgrounds along Hwy 13 corridor. Water available in camp but bring a filter.",
      bestSeasonTier: "1st Rifle",
      bestArrivalDate: "Oct 12",
      typicalHuntLength: "5 days",
      trophyExpectation: "Good opportunity unit — more about filling tags than trophy hunting. 240-260 class bulls common. High success rate makes this ideal for first western elk hunt.",
      cellService: "Better than Units 11/211 — Verizon works along Hwy 13. Interior still limited.",
      proTip: "This is a great 'first western elk hunt' unit. High tag quota, good access, and high success rate. Perfect for learning the game before investing big points in premium units.",
    },
  },
  {
    id: "co-elk-003",
    stateId: "CO",
    speciesId: "elk",
    unitCode: "3",
    unitName: "White River",
    successRate: 0.18,
    trophyRating: 7,
    pointsRequiredResident: 1,
    pointsRequiredNonresident: 3,
    terrainType: ["Sagebrush", "Mixed"],
    pressureLevel: "Low",
    elevationRange: [6000, 9500],
    publicLandPct: 0.35,
    tagQuotaNonresident: 80,
    notes: "2nd/3rd Rifle limited draw. Sagebrush flats and migration corridors.",
    nearestAirport: "DEN (4 hrs) or HDN (1.5 hrs)",
    driveTimeFromAirport: "4 hours from DEN, 1.5 hours from HDN (Steamboat)",
    tacticalNotes: {
      accessMethod: "More limited access than Units 4/11. Mix of private and public land. BLM access points well-marked. 4WD essential on most roads.",
      glassingStrategy: "This unit excels during late season when elk are migrating through sage flats. Set up on high points overlooking migration corridors between sage and timber. Dawn and dusk are money time.",
      campingOptions: "Limited dispersed camping compared to other NW CO units. Some BLM camping available but research access points on onX before arriving.",
      bestSeasonTier: "3rd Rifle / 4th Rifle",
      bestArrivalDate: "Nov 3 for 3rd Rifle",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "Quality unit — 280-320 class bulls. Lower pressure than Units 4/11 due to fewer tags. Late-season migration concentrates animals.",
      cellService: "Limited. Verizon has some coverage on ridgetops.",
      proTip: "Late-season migration is the key to this unit. Elk move through predictable corridors when snow pushes them to lower elevations. Check weather forecasts — a good storm right before your hunt is ideal.",
    },
  },

  // ============================================================================
  // Colorado Mule Deer
  // ============================================================================
  {
    id: "co-md-011",
    stateId: "CO",
    speciesId: "mule_deer",
    unitCode: "11",
    unitName: "White River",
    successRate: 0.32,
    trophyRating: 7,
    pointsRequiredResident: 1,
    pointsRequiredNonresident: 3,
    terrainType: ["Sagebrush", "Timber"],
    pressureLevel: "Moderate",
    elevationRange: [6500, 9500],
    publicLandPct: 0.45,
    tagQuotaNonresident: 100,
    notes: "3rd Rifle rut hunt. Bucks migrate from high summer ranges to sage flats.",
    nearestAirport: "DEN (3.5 hrs) or GJT (2 hrs)",
    driveTimeFromAirport: "3.5 hours from DEN via I-70 → Hwy 13",
    tacticalNotes: {
      accessMethod: "Same road network as elk Unit 11. Truck-based glassing is the primary tactic. Work sage ridges and rimrock edges.",
      glassingStrategy: "3rd Rifle timing coincides with mule deer pre-rut. Glass sage flats at dawn and dusk — bucks are on their feet chasing does. Focus on rimrock edges and cedar breaks where bucks bed midday.",
      campingOptions: "Same camping options as elk Unit 11. Camp near ridge systems for quick morning glass sessions.",
      bestSeasonTier: "3rd Rifle (Nov 5-13)",
      bestArrivalDate: "Nov 3",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "150-170 class bucks. This is NW Colorado mule deer at its best. 3rd Rifle rut timing is prime. Big-bodied, heavy-antlered bucks migrate through sage parks.",
      proTip: "Combine with a leftover cow elk OTC tag for a two-species trip. Glass for mule deer bucks at dawn and dusk, and hunt cow elk during midday in the timber. Maximum value per trip.",
    },
  },
  {
    id: "co-md-211",
    stateId: "CO",
    speciesId: "mule_deer",
    unitCode: "211",
    unitName: "Bear's Ears",
    successRate: 0.35,
    trophyRating: 8,
    pointsRequiredResident: 1,
    pointsRequiredNonresident: 3,
    terrainType: ["Sagebrush", "Mixed"],
    pressureLevel: "Moderate",
    elevationRange: [6000, 9000],
    publicLandPct: 0.45,
    tagQuotaNonresident: 75,
    notes: "150-170\" trophy class during 3rd Rifle rut season.",
    nearestAirport: "DEN (3.5 hrs) or GJT (2.5 hrs)",
    driveTimeFromAirport: "3.5 hours from DEN",
    tacticalNotes: {
      accessMethod: "Same access as elk Unit 211. Focus on lower-elevation sage/oak brush draws.",
      glassingStrategy: "Unit 211 concentrates mule deer along the White River drainage during rut. Glass from high points above oak brush draws at dawn. Bucks chase does through semi-open terrain — catchable with patience.",
      campingOptions: "Same as elk options. Camp near drainage overlooks.",
      bestSeasonTier: "3rd Rifle (Nov 5-13)",
      bestArrivalDate: "Nov 3",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "Trophy unit — 160-180 class bucks possible. High success rate with good shot opportunities during rut. This is one of the better NR mule deer units in CO.",
      proTip: "The rut concentrates bucks in ways that make them more visible than any other time of year. Be patient, glass hard, and cover ground with your optics, not your boots.",
    },
  },

  // ============================================================================
  // Colorado Bear
  // ============================================================================
  {
    id: "co-bear-011",
    stateId: "CO",
    speciesId: "bear",
    unitCode: "11",
    unitName: "White River",
    successRate: 0.15,
    trophyRating: 5,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 0,
    terrainType: ["Timber", "Mixed"],
    pressureLevel: "Low",
    elevationRange: [7000, 10000],
    publicLandPct: 0.45,
    tagQuotaNonresident: 200,
    notes: "OTC bear tags in many units. September archery over natural food sources is prime.",
    nearestAirport: "DEN (3.5 hrs)",
    driveTimeFromAirport: "3.5 hours from DEN",
    tacticalNotes: {
      accessMethod: "Same road network as elk. Bears are typically found in timber and oak brush draws.",
      glassingStrategy: "Glass oak brush hillsides at dawn and dusk. Bears feed on acorns and berries in September. South-facing slopes with oak brush are productive.",
      campingOptions: "Same as elk camping options.",
      bestSeasonTier: "Archery (Sep) / 2nd Rifle (Oct)",
      bestArrivalDate: "Sep 5 for archery, Oct 22 for rifle",
      typicalHuntLength: "5 days",
      trophyExpectation: "Color-phase bears available. Chocolate and cinnamon bears in NW CO. Average bears run 200-300 lbs.",
      proTip: "OTC bear tags make this a great add-on to any CO elk/deer trip. Buy the tag as insurance — if you see a bear while elk hunting, you're already tagged.",
    },
  },
  {
    id: "co-bear-076",
    stateId: "CO",
    speciesId: "bear",
    unitCode: "76",
    unitName: "San Juan",
    successRate: 0.20,
    trophyRating: 6,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 0,
    terrainType: ["Timber", "Alpine"],
    pressureLevel: "Low",
    elevationRange: [7500, 11000],
    publicLandPct: 0.70,
    tagQuotaNonresident: 150,
    notes: "High-country bear. Oak brush and aspen. Fall season over acorns and berries.",
    nearestAirport: "MTJ (Montrose, 1.5 hrs) or DEN (5 hrs)",
    driveTimeFromAirport: "1.5 hours from Montrose, 5 hours from DEN",
    tacticalNotes: {
      accessMethod: "Good forest road access in the San Juans. 4WD required. Some steep terrain but roadside glassing is productive.",
      glassingStrategy: "Glass oak brush mountainsides in morning light. Bears feed heavily on acorns in September-October before denning. South-facing slides with berry bushes are money spots.",
      campingOptions: "Excellent National Forest dispersed camping. High-country camps at 8,000-9,000 ft. Cold nights in October.",
      bestSeasonTier: "September archery / early rifle",
      bestArrivalDate: "Sep 10",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "Higher quality bears than Unit 11. 70% public land means more undisturbed habitat. Color-phase bears common in the San Juans.",
      proTip: "San Juan bears den earlier than NW CO bears due to higher elevation. Hunt September for best activity. October can be hit-or-miss as bears start entering dens.",
    },
  },

  // ============================================================================
  // Colorado Moose
  // ============================================================================
  {
    id: "co-moose-001",
    stateId: "CO",
    speciesId: "moose",
    unitCode: "1",
    unitName: "North Park",
    successRate: 0.85,
    trophyRating: 7,
    pointsRequiredResident: 10,
    pointsRequiredNonresident: 20,
    terrainType: ["Timber", "Mixed"],
    pressureLevel: "Low",
    elevationRange: [8000, 10000],
    publicLandPct: 0.50,
    tagQuotaNonresident: 5,
    notes: "Once-in-a-lifetime. 20+ year wait for NR. Willow creek bottoms and spruce/fir.",
    nearestAirport: "DEN (3 hrs)",
    driveTimeFromAirport: "3 hours from DEN via I-70 → Hwy 9 N to Walden",
    tacticalNotes: {
      accessMethod: "Mix of road access and moderate hikes. Willow creek bottoms accessible from county roads. Some private land — check onX boundaries carefully.",
      glassingStrategy: "Moose are predictable. Glass willow creek bottoms at dawn and dusk. Bulls feed in willows and bed in adjacent spruce/fir timber. September rut is best — bulls respond to cow calls.",
      campingOptions: "State forest campgrounds and dispersed NF camping. North Park is beautiful high-country basin.",
      bestSeasonTier: "September rifle",
      bestArrivalDate: "Sep 12",
      typicalHuntLength: "7-10 days",
      trophyExpectation: "Bull moose with 35-45 inch spreads. 85% success rate when drawn. This is a once-in-a-lifetime tag — take your time and enjoy the hunt.",
      proTip: "Once-in-a-lifetime means exactly that. Don't rush this hunt. Plan 7-10 days, scout the first 2 days, and be selective. You'll never draw this tag again in CO.",
    },
  },

  // ============================================================================
  // Wyoming Elk
  // ============================================================================
  {
    id: "wy-elk-035",
    stateId: "WY",
    speciesId: "elk",
    unitCode: "35",
    unitName: "Bighorn Mountains",
    successRate: 0.32,
    trophyRating: 7,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 5,
    terrainType: ["Timber", "Alpine"],
    pressureLevel: "Low",
    elevationRange: [7500, 11000],
    publicLandPct: 0.70,
    tagQuotaNonresident: 50,
    notes: "Premier DIY. No grizzly/wolf. Timbered canyons and high-plateau meadows.",
    nearestAirport: "SHR (Sheridan, 1 hr) or BIL (2 hrs)",
    driveTimeFromAirport: "1 hour from Sheridan, 2 hours from Billings MT",
    tacticalNotes: {
      accessMethod: "Forest roads access the Bighorns from east and west sides. 4WD essential. Some trailhead-based access for deeper penetration. Roads close with early snow.",
      glassingStrategy: "Glass high meadows and park openings from timbered ridgelines. The Bighorns have excellent alpine meadow systems where elk feed. Morning and evening glass sessions from high vantage points.",
      campingOptions: "Bighorn National Forest campgrounds and dispersed camping. High-country camps at 8,000-9,000 ft. Bring cold-weather gear — October nights drop below freezing.",
      bestSeasonTier: "General Rifle (Oct)",
      bestArrivalDate: "Oct 1",
      typicalHuntLength: "7 days",
      trophyExpectation: "280-320 class bulls. The Bighorns are one of the best DIY elk areas in WY. No grizzly or wolf pressure means animals are less nocturnal than Yellowstone-area units.",
      waterSources: "Mountain streams, springs, and alpine lakes throughout. No water concerns.",
      cellService: "Very limited throughout the Bighorns. Download everything offline.",
      proTip: "The no-grizzly factor is huge. You can hang meat at camp without bear boxes, call more aggressively, and hunt later into dark without predator concerns. This changes your entire approach compared to western WY.",
    },
  },
  {
    id: "wy-elk-100",
    stateId: "WY",
    speciesId: "elk",
    unitCode: "100",
    unitName: "Desert Elk",
    successRate: 0.85,
    trophyRating: 8,
    pointsRequiredResident: 2,
    pointsRequiredNonresident: 5,
    terrainType: ["Desert", "Sagebrush"],
    pressureLevel: "Low",
    elevationRange: [5000, 7500],
    publicLandPct: 0.60,
    tagQuotaNonresident: 25,
    notes: "80-90% success. Glassing-dependent. Minimal steep hiking.",
    nearestAirport: "SLC (4 hrs) or RKS (2 hrs)",
    driveTimeFromAirport: "4 hours from SLC via I-80 E, 2 hours from Rock Springs",
    tacticalNotes: {
      accessMethod: "Truck-accessible desert terrain. 4WD helpful but not essential on main BLM roads. Flat to rolling terrain — no mountain climbing required.",
      glassingStrategy: "Pure glassing hunt. Set up on rimrock edges and sage ridges, glass vast expanses of open country. Bulls are visible at 1-2 miles in this terrain. Spot from vehicle, plan stalk.",
      campingOptions: "BLM dispersed camping throughout. Flat, open camping with good vehicle access. Bring wind shelter — it blows constantly. Water is scarce — pack everything in.",
      bestSeasonTier: "Late Season (Nov)",
      bestArrivalDate: "Nov 1",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "300-340 class bulls. Desert elk grow big in this nutrient-rich sage habitat. The low tag numbers and 85% success rate make this a premier tag. Expect shots at 300-500 yards.",
      waterSources: "Scarce. Stock tanks and windmill-fed troughs. Pack water for camp.",
      cellService: "Limited. Some Verizon coverage on high points. AT&T minimal.",
      proTip: "This is a glasser's paradise. Bring the best optics you can afford — 15x binos on a tripod minimum. Most animals are spotted at 1+ miles. Wind is your biggest challenge. Plan stalks using terrain features.",
    },
  },

  // ============================================================================
  // Wyoming Mule Deer
  // ============================================================================
  {
    id: "wy-md-145",
    stateId: "WY",
    speciesId: "mule_deer",
    unitCode: "145",
    unitName: "Wyoming Range",
    successRate: 0.45,
    trophyRating: 7,
    pointsRequiredResident: 1,
    pointsRequiredNonresident: 4,
    terrainType: ["Sagebrush", "Mixed"],
    pressureLevel: "Moderate",
    elevationRange: [6500, 9500],
    publicLandPct: 0.55,
    tagQuotaNonresident: 60,
    nearestAirport: "JAC (2 hrs) or SLC (4 hrs)",
    driveTimeFromAirport: "2 hours from Jackson, 4 hours from SLC",
    tacticalNotes: {
      accessMethod: "Mix of BLM access and National Forest roads. 4WD recommended. Some private land borders — check onX maps carefully.",
      glassingStrategy: "Glass sage basins and aspens draws. Wyoming Range mule deer use the sage-to-timber transition extensively. Late-season rut concentrates bucks in visible terrain.",
      campingOptions: "NF dispersed camping. Bridger-Teton NF campgrounds. Cold-weather camping in November.",
      bestSeasonTier: "General Rifle / Late Season",
      bestArrivalDate: "Oct 25 for late rut",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "160-180 class bucks. Wyoming Range has historically produced some of the best mule deer in the state. Rut timing is key — late October through November.",
      proTip: "Wyoming Range mule deer respond well to the first significant snowfall. Monitor weather and time your hunt to coincide with a cold front that pushes deer from high country to mid-elevation sage.",
    },
  },

  // ============================================================================
  // Wyoming Moose
  // ============================================================================
  {
    id: "wy-moose-001",
    stateId: "WY",
    speciesId: "moose",
    unitCode: "1",
    unitName: "Teton / Upper Snake",
    successRate: 0.90,
    trophyRating: 9,
    pointsRequiredResident: 5,
    pointsRequiredNonresident: 15,
    terrainType: ["Timber", "Alpine"],
    pressureLevel: "Low",
    elevationRange: [6500, 9500],
    publicLandPct: 0.80,
    tagQuotaNonresident: 3,
    notes: "World-class Shiras moose. 15+ year NR wait. Apply every year with point purchase.",
    nearestAirport: "JAC (30 min)",
    driveTimeFromAirport: "30 minutes from Jackson Hole airport",
    tacticalNotes: {
      accessMethod: "Excellent road and trail access in Teton area. Mix of NF roads, hiking trails, and river bottom access. 4WD helpful.",
      glassingStrategy: "Glass willow flats along Snake River and tributary streams. Moose are visible feeding in willows at dawn and dusk. September rut — bulls respond to cow calls and are less wary.",
      campingOptions: "Bridger-Teton NF campgrounds and dispersed camping. Fall camping in Jackson Hole is stunning. Book early — October is peak tourist season too.",
      bestSeasonTier: "September rifle",
      bestArrivalDate: "Sep 15",
      typicalHuntLength: "7-10 days",
      trophyExpectation: "45-55 inch bulls. World-class Shiras moose. Near-guaranteed success when drawn. This is a once-in-a-lifetime hunt in the shadow of the Tetons.",
      proTip: "This is arguably the best Shiras moose unit in the world. 15+ year NR wait but near-100% success. Buy points every year starting now. The earlier you start, the sooner you draw this bucket-list tag.",
    },
  },

  // ============================================================================
  // Montana Elk
  // ============================================================================
  {
    id: "mt-elk-general",
    stateId: "MT",
    speciesId: "elk",
    unitCode: "General",
    unitName: "Big Game Combo",
    successRate: 0.25,
    trophyRating: 6,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 2,
    terrainType: ["Timber", "Mixed"],
    pressureLevel: "Moderate",
    elevationRange: [4500, 10000],
    publicLandPct: 0.50,
    tagQuotaNonresident: 5200,
    notes: "Combo license includes elk + deer. Burn every 3 years with 2 preference points.",
    nearestAirport: "BZN (varies) or BIL (varies)",
    driveTimeFromAirport: "Varies by district — MT is huge. 1-5 hours from major airports.",
    tacticalNotes: {
      accessMethod: "Varies by district. Generally good road access on NF and BLM lands. MT has excellent public land access laws. Block Management program provides free access to private lands.",
      glassingStrategy: "District-dependent. SW MT: glass alpine basins and timber edges. Eastern MT: glass prairie coulees and river bottoms. Block Management areas are underutilized gems.",
      campingOptions: "Extensive NF camping throughout MT. Block Management areas sometimes allow camping. 5+ week season means you can camp comfortably with winter gear.",
      bestSeasonTier: "General Rifle (late Oct / early Nov)",
      bestArrivalDate: "Oct 25 — after opening-week pressure",
      typicalHuntLength: "7-10 days",
      trophyExpectation: "Solid opportunity unit. 260-300 class bulls. The value is getting elk + deer on one license. Quality improves in remote districts.",
      proTip: "The combo license is the best deal in western hunting. One draw gives you elk, deer, fishing, and birds. Apply every year — with 2 preference points you'll draw every 2-3 years. Use Block Management for access to private land herds.",
    },
  },

  // ============================================================================
  // Montana Bear
  // ============================================================================
  {
    id: "mt-bear-spring",
    stateId: "MT",
    speciesId: "bear",
    unitCode: "Spring",
    unitName: "Spring Bear General",
    successRate: 0.30,
    trophyRating: 6,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 0,
    terrainType: ["Timber", "Mixed"],
    pressureLevel: "Low",
    elevationRange: [4000, 8000],
    publicLandPct: 0.55,
    tagQuotaNonresident: 1000,
    notes: "OTC spring bear. Spot-and-stalk on south-facing slopes with early green-up. Apr-May.",
    nearestAirport: "BZN or MSO (varies)",
    driveTimeFromAirport: "Varies — 1-3 hours depending on area",
    tacticalNotes: {
      accessMethod: "Road-accessible. Glass south-facing slopes from truck or roadside pullouts. Bears emerge on south-facing slides with early green-up.",
      glassingStrategy: "Classic spot-and-stalk. Set up on high points overlooking south-facing slopes with new grass. Bears are visible at distance on open hillsides. Glass afternoon when bears are most active post-den.",
      campingOptions: "NF campgrounds and dispersed camping. April-May weather is variable — be prepared for snow and mud.",
      bestSeasonTier: "Spring (April-May)",
      bestArrivalDate: "April 20",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "Color-phase bears common in MT. Cinnamon and blonde bears. Boars run 250-400 lbs post-den. Fur quality is prime in spring.",
      proTip: "Spring bear is the most underrated hunt in the West. OTC tag, low pressure, beautiful spring weather, and excellent spot-and-stalk opportunity. It's a perfect 'off-season' trip to scratch the hunting itch.",
    },
  },

  // ============================================================================
  // Montana Moose
  // ============================================================================
  {
    id: "mt-moose-general",
    stateId: "MT",
    speciesId: "moose",
    unitCode: "Special",
    unitName: "Moose Special Permit",
    successRate: 0.85,
    trophyRating: 7,
    pointsRequiredResident: 8,
    pointsRequiredNonresident: 15,
    terrainType: ["Timber", "Mixed"],
    pressureLevel: "Low",
    elevationRange: [4500, 8000],
    publicLandPct: 0.50,
    tagQuotaNonresident: 10,
    notes: "Bonus point squared system for special permits. Long-term play with high reward.",
    nearestAirport: "BZN or MSO (varies by permit area)",
    driveTimeFromAirport: "Varies — 1-4 hours",
    tacticalNotes: {
      accessMethod: "Varies by permit area. Generally good road access to willow bottoms. Some areas require moderate hikes.",
      glassingStrategy: "Glass willow creek bottoms and river drainages. Moose are predictable — they feed in willows at dawn/dusk and bed in adjacent timber. September rut bulls are responsive to calling.",
      campingOptions: "NF camping near permit areas. Research specific area access before applying.",
      bestSeasonTier: "September - October",
      bestArrivalDate: "Sep 15",
      typicalHuntLength: "7-10 days",
      trophyExpectation: "Solid Shiras moose. 35-45 inch bulls. Bonus squared system means your odds improve exponentially. Long-term investment.",
      proTip: "MT moose uses the bonus squared system, meaning 5 points gives you 36x the chances of a zero-point applicant. Start buying points now — every year you wait makes the math worse.",
    },
  },

  // ============================================================================
  // Montana Whitetail
  // ============================================================================
  {
    id: "mt-whitetail-general",
    stateId: "MT",
    speciesId: "whitetail",
    unitCode: "General",
    unitName: "General Combo Whitetail",
    successRate: 0.35,
    trophyRating: 6,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 2,
    terrainType: ["Timber", "Prairie"],
    pressureLevel: "Moderate",
    elevationRange: [3500, 6000],
    publicLandPct: 0.35,
    tagQuotaNonresident: 5200,
    notes: "Included with combo license. River-bottom and coulee whitetail. Rut hunts in November.",
    nearestAirport: "BIL (varies) or MSO (varies)",
    driveTimeFromAirport: "Varies by district",
    tacticalNotes: {
      accessMethod: "River-bottom access via public land and Block Management. Eastern MT prairie whitetail in coulees. Western MT in river valleys.",
      glassingStrategy: "Glass river-bottom timber edges and coulee lips. November rut pushes bucks into the open. Stand hunting over scrapes and rub lines is effective in eastern MT.",
      campingOptions: "Mix of NF camping and motels in small towns. November weather can be brutal — plan for cold.",
      bestSeasonTier: "General Rifle (Nov rut)",
      bestArrivalDate: "Nov 10 for peak rut",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "130-160 class bucks. Not Kansas-caliber but a bonus tag on your combo license. Some eastern MT areas produce surprisingly good whitetail.",
      proTip: "The whitetail tag comes FREE with your combo license. If you draw the combo for elk, bring a whitetail setup too. November rut timing overlaps perfectly with late-season elk.",
    },
  },

  // ============================================================================
  // Nevada Elk
  // ============================================================================
  {
    id: "nv-elk-231",
    stateId: "NV",
    speciesId: "elk",
    unitCode: "231",
    unitName: "Jarbidge",
    successRate: 0.55,
    trophyRating: 9,
    pointsRequiredResident: 4,
    pointsRequiredNonresident: 8,
    terrainType: ["Alpine", "Timber"],
    pressureLevel: "Low",
    elevationRange: [6000, 10000],
    publicLandPct: 0.80,
    tagQuotaNonresident: 5,
    notes: "Trophy quality. Bonus squared system. Long-term investment.",
    nearestAirport: "EKO (Elko, 2.5 hrs) or BOI (4 hrs)",
    driveTimeFromAirport: "2.5 hours from Elko on remote roads, 4 hours from Boise",
    tacticalNotes: {
      accessMethod: "Remote. 4WD high-clearance vehicle mandatory. Last 40 miles on unimproved roads. Spare tire and recovery gear essential. No services for 100+ miles.",
      glassingStrategy: "Glass alpine basins and timbered ridges. NV elk units are vast and open — use 15x binos on tripod. Animals visible at extreme distances. Plan multi-hour stalks across rugged terrain.",
      campingOptions: "Primitive dispersed camping only. Pack in all water, food, fuel. Nearest town (Jarbidge) has very limited services.",
      bestSeasonTier: "Late Rifle (Oct-Nov)",
      bestArrivalDate: "Oct 10",
      typicalHuntLength: "7-10 days",
      trophyExpectation: "330-370 class bulls. NV elk are trophy-class by nature — limited tags and vast habitat produce exceptional animals. This is a bucket-list hunt when drawn.",
      waterSources: "Mountain streams and springs. Pack water treatment. Camp water supply may need to be packed in.",
      cellService: "None. Satellite communicator (Garmin inReach) strongly recommended for safety.",
      proTip: "Nevada elk is a commitment hunt. Remote, rugged, and wild. But the animals are extraordinary. Invest in the squared bonus points now, and when you finally draw in 8-10 years, it'll be the hunt of a lifetime. Bring a sat phone.",
    },
  },

  // ============================================================================
  // Idaho Elk
  // ============================================================================
  {
    id: "id-elk-sawtooth",
    stateId: "ID",
    speciesId: "elk",
    unitCode: "36",
    unitName: "Sawtooth Zone",
    successRate: 0.20,
    trophyRating: 6,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 0,
    terrainType: ["Timber", "Alpine"],
    pressureLevel: "Moderate",
    elevationRange: [5000, 10000],
    publicLandPct: 0.85,
    tagQuotaNonresident: 300,
    notes: "Pure random draw. No points needed. Wild card opportunity every year.",
    nearestAirport: "SUN (Sun Valley, 1 hr) or BOI (2.5 hrs)",
    driveTimeFromAirport: "1 hour from Sun Valley, 2.5 hours from Boise via Hwy 21",
    tacticalNotes: {
      accessMethod: "Sawtooth NF roads and trailheads. 4WD required. Mix of road-accessible and backcountry access. Excellent public land — 85% NF.",
      glassingStrategy: "Glass alpine basins and timbered meadow edges. The Sawtooths have classic Idaho mountain terrain. Elk use high-country parks and basin floors in September-October.",
      campingOptions: "Excellent NF camping throughout. Developed campgrounds and dispersed sites. Stanley area has services (gas, food, lodging).",
      bestSeasonTier: "General Rifle (Oct-Nov)",
      bestArrivalDate: "Oct 12",
      typicalHuntLength: "7 days",
      trophyExpectation: "Opportunity unit — 250-280 class bulls. Lower success rate but your NR license IS your tag. Hunt every year with no draw needed for general season.",
      cellService: "Limited in Stanley area. None in backcountry. Sat communicator recommended.",
      proTip: "Your NR hunting license IS your general elk tag in Idaho. No draw needed. This means you can hunt ID elk every single year as a guaranteed opportunity. Apply for controlled hunts as a bonus, but the general tag is your safety net.",
    },
  },

  // ============================================================================
  // Idaho Bear
  // ============================================================================
  {
    id: "id-bear-spring",
    stateId: "ID",
    speciesId: "bear",
    unitCode: "Spring",
    unitName: "Spring Controlled",
    successRate: 0.35,
    trophyRating: 6,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 0,
    terrainType: ["Timber", "Mixed"],
    pressureLevel: "Low",
    elevationRange: [4000, 8000],
    publicLandPct: 0.80,
    tagQuotaNonresident: 500,
    notes: "Spring controlled hunt. Spot-and-stalk. Random draw, no points. Great success rates.",
    nearestAirport: "BOI (varies)",
    driveTimeFromAirport: "2-4 hours depending on unit",
    tacticalNotes: {
      accessMethod: "Road-accessible for most spring bear areas. Glass south-facing slopes from truck or roadside vantage points.",
      glassingStrategy: "Same as MT spring bear — glass south-facing slopes with new grass and berry patches. Bears are visible at distance on open hillsides. Afternoon is prime activity time.",
      campingOptions: "NF dispersed camping. Spring conditions — mud and variable weather. Bring cold-weather gear.",
      bestSeasonTier: "Spring (April-June)",
      bestArrivalDate: "April 25",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "Good-sized black bears. Color-phase common in central ID. Random draw means no points needed — just apply.",
      proTip: "Idaho spring bear is a random draw with no points. Apply every single year — it costs nothing extra. If you draw, it's an excellent off-season hunting trip that won't conflict with fall elk plans.",
    },
  },

  // ============================================================================
  // Idaho Moose
  // ============================================================================
  {
    id: "id-moose-controlled",
    stateId: "ID",
    speciesId: "moose",
    unitCode: "Controlled",
    unitName: "Moose Controlled Hunt",
    successRate: 0.90,
    trophyRating: 7,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 0,
    terrainType: ["Timber", "Mixed"],
    pressureLevel: "Low",
    elevationRange: [5000, 8000],
    publicLandPct: 0.75,
    tagQuotaNonresident: 15,
    notes: "Pure random draw. No points. Apply every year — it's a lottery ticket.",
    nearestAirport: "BOI or IDA (varies by unit)",
    driveTimeFromAirport: "2-4 hours depending on unit",
    tacticalNotes: {
      accessMethod: "Varies by controlled hunt unit. Generally good road access to willow creek drainages.",
      glassingStrategy: "Glass willow bottoms and creek drainages. Moose are predictable feeders. September rut makes bulls responsive to calling.",
      campingOptions: "NF camping near controlled hunt areas. Research your specific unit before applying.",
      bestSeasonTier: "September - October",
      bestArrivalDate: "Sep 20",
      typicalHuntLength: "7-10 days",
      trophyExpectation: "Quality Shiras moose. Random draw means no waiting — you could draw year one or year twenty. 90% success when drawn.",
      proTip: "Idaho moose is a pure lottery — no points, no strategy, just apply for $0 extra (included with your hunting license). Someday you'll get the call. Apply every single year.",
    },
  },

  // ============================================================================
  // Idaho Whitetail
  // ============================================================================
  {
    id: "id-whitetail-general",
    stateId: "ID",
    speciesId: "whitetail",
    unitCode: "General",
    unitName: "Northern Idaho Whitetail",
    successRate: 0.40,
    trophyRating: 6,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 0,
    terrainType: ["Timber", "Mixed"],
    pressureLevel: "Moderate",
    elevationRange: [2500, 5500],
    publicLandPct: 0.60,
    tagQuotaNonresident: 1000,
    notes: "Comes with your NR hunting license. Panhandle and Clearwater regions are best.",
    nearestAirport: "LWS (Lewiston) or GEG (Spokane, WA)",
    driveTimeFromAirport: "1-2 hours from Lewiston, 2-3 hours from Spokane",
    tacticalNotes: {
      accessMethod: "Good road access on NF lands. Logging roads provide excellent whitetail access. Mix of public and industrial timber land.",
      glassingStrategy: "Not a glassing hunt — still-hunting and stand hunting are primary tactics. Hunt creek bottoms, clearcut edges, and agricultural fields. November rut is prime.",
      campingOptions: "NF campgrounds and dispersed camping. Small-town motels in Orofino, Grangeville, Moscow.",
      bestSeasonTier: "General Rifle (Oct-Nov)",
      bestArrivalDate: "Nov 10 for peak rut",
      typicalHuntLength: "5 days",
      trophyExpectation: "Solid whitetail — 130-150 class bucks in the Clearwater and Panhandle regions. Not Kansas, but a free tag on your NR license.",
      proTip: "Your NR hunting license includes a whitetail tag at no extra cost. If you're in Idaho for elk, extend your trip a few days for whitetail in the Panhandle region. November rut timing overlaps with late elk season.",
    },
  },

  // ============================================================================
  // Arizona Elk
  // ============================================================================
  {
    id: "az-elk-001",
    stateId: "AZ",
    speciesId: "elk",
    unitCode: "1",
    unitName: "Kaibab",
    successRate: 0.45,
    trophyRating: 9,
    pointsRequiredResident: 5,
    pointsRequiredNonresident: 10,
    terrainType: ["Timber", "Mixed"],
    pressureLevel: "Low",
    elevationRange: [7000, 9000],
    publicLandPct: 0.65,
    tagQuotaNonresident: 15,
    notes: "Trophy unit. Bonus point system (not squared).",
    nearestAirport: "FLG (Flagstaff, 2.5 hrs) or PHX (4.5 hrs)",
    driveTimeFromAirport: "2.5 hours from Flagstaff, 4.5 hours from Phoenix",
    tacticalNotes: {
      accessMethod: "Kaibab NF roads. 4WD helpful. Mix of ponderosa pine and meadow systems. Less rugged than CO/WY mountain terrain.",
      glassingStrategy: "Glass meadow systems in ponderosa pine forest. AZ elk are large-bodied and often visible at moderate distances in the open park-like forests. Morning and evening feeding in meadows.",
      campingOptions: "Kaibab NF dispersed camping and developed campgrounds. Fall weather is pleasant — cool nights, warm afternoons. Less extreme than mountain states.",
      bestSeasonTier: "Late Rifle (Nov)",
      bestArrivalDate: "Nov 12",
      typicalHuntLength: "7 days",
      trophyExpectation: "340-380+ class bulls. AZ Kaibab elk are among the largest in North America. Limited tags mean low pressure and unhunted animals. This is a true trophy hunt.",
      proTip: "AZ bonus points build linearly (not squared), so the point advantage grows slower than NV. But the quality when you draw is exceptional. Start building points early and be patient — this is a 10+ year investment.",
    },
  },

  // ============================================================================
  // Arizona Bear
  // ============================================================================
  {
    id: "az-bear-023",
    stateId: "AZ",
    speciesId: "bear",
    unitCode: "23",
    unitName: "Mogollon Rim",
    successRate: 0.25,
    trophyRating: 5,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 0,
    terrainType: ["Timber", "Mixed"],
    pressureLevel: "Low",
    elevationRange: [6000, 8500],
    publicLandPct: 0.70,
    tagQuotaNonresident: 100,
    notes: "Fall bear over acorns. Separate draw from big game. Spring hunts also available.",
    nearestAirport: "PHX (2 hrs)",
    driveTimeFromAirport: "2 hours from Phoenix via Hwy 87 N",
    tacticalNotes: {
      accessMethod: "Good forest road access on the Mogollon Rim. 4WD helpful but not required for main roads. Scenic pine/oak forest.",
      glassingStrategy: "Glass oak brush hillsides for bears feeding on acorns. Fall color makes spotting bears easier. South-facing slopes with oak brush are most productive.",
      campingOptions: "Coconino and Tonto NF camping. Rim area has developed campgrounds. Fall weather is ideal — cool nights, warm days.",
      bestSeasonTier: "Fall (Sep-Nov)",
      bestArrivalDate: "Oct 1",
      typicalHuntLength: "5 days",
      trophyExpectation: "Average-sized black bears. Less color-phase variety than CO/MT. Good opportunity hunt in beautiful Rim Country terrain.",
      proTip: "AZ bear is a separate draw from the big game draw (different deadline). Easy to overlook — put it on your calendar. Low cost, good opportunity, and doesn't conflict with elk/deer applications.",
    },
  },

  // ============================================================================
  // Utah Elk
  // ============================================================================
  {
    id: "ut-elk-general",
    stateId: "UT",
    speciesId: "elk",
    unitCode: "General",
    unitName: "General Any Bull",
    successRate: 0.15,
    trophyRating: 5,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 0,
    terrainType: ["Mixed", "Timber"],
    pressureLevel: "High",
    elevationRange: [6000, 11000],
    publicLandPct: 0.50,
    tagQuotaNonresident: 1000,
    notes: "OTC general season. High pressure but accessible.",
    nearestAirport: "SLC (1-2 hrs)",
    driveTimeFromAirport: "1-2 hours from SLC to most general units",
    tacticalNotes: {
      accessMethod: "Good road access but high hunter density on public land. Get deep — hike past where most hunters go. Trailhead parking fills up opening morning.",
      glassingStrategy: "Difficult glassing due to timber-heavy terrain. Still-hunting and calling more effective than pure glassing. Find areas with fewer roads = fewer hunters.",
      campingOptions: "NF campgrounds and dispersed camping. Reserve developed sites early. Dispersed camping fills up during general season.",
      bestSeasonTier: "Any Weapon (Oct 7-15)",
      bestArrivalDate: "Oct 5 for scouting",
      typicalHuntLength: "7-9 days",
      trophyExpectation: "Opportunity unit — 240-260 class bulls. High pressure means lower trophy potential, but the ease of drawing and proximity to SLC make it accessible. Hike deep for better quality.",
      proTip: "UT general elk is a pressure game. The hunters who succeed either go deep into the backcountry or hunt early/late when others are in camp. Mid-week hunting (Tue-Thu) sees significantly less pressure than weekends.",
    },
  },

  // ============================================================================
  // Utah Moose
  // ============================================================================
  {
    id: "ut-moose-wasatch",
    stateId: "UT",
    speciesId: "moose",
    unitCode: "Wasatch",
    unitName: "Wasatch Mountains",
    successRate: 0.90,
    trophyRating: 8,
    pointsRequiredResident: 15,
    pointsRequiredNonresident: 20,
    terrainType: ["Timber", "Alpine"],
    pressureLevel: "Low",
    elevationRange: [6000, 10000],
    publicLandPct: 0.55,
    tagQuotaNonresident: 3,
    notes: "Once-in-a-lifetime. 20+ year NR wait. Some of the biggest Shiras moose in the country.",
    nearestAirport: "SLC (1 hr)",
    driveTimeFromAirport: "1 hour from SLC to Wasatch trailheads",
    tacticalNotes: {
      accessMethod: "Good road and trail access from Wasatch front communities. Some areas accessible by day-hike from trailheads.",
      glassingStrategy: "Glass willow creek bottoms and high-mountain basins. Wasatch moose are visible in alpine willows. September rut is best for finding bulls.",
      campingOptions: "NF campgrounds in Wasatch. Close enough to SLC for motel-based hunting if preferred.",
      bestSeasonTier: "September",
      bestArrivalDate: "Sep 15",
      typicalHuntLength: "7-10 days",
      trophyExpectation: "45-55 inch bulls. Some of the largest Shiras moose in the lower 48. Once-in-a-lifetime tag — be selective.",
      proTip: "UT OIAL moose is a 20+ year NR commitment. Start buying points ($75/yr) as early as possible. The close proximity to SLC airport makes this one of the most logistically convenient moose hunts in the West.",
    },
  },

  // ============================================================================
  // New Mexico Elk
  // ============================================================================
  {
    id: "nm-elk-034",
    stateId: "NM",
    speciesId: "elk",
    unitCode: "34",
    unitName: "Valles Caldera",
    successRate: 0.50,
    trophyRating: 8,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 0,
    terrainType: ["Mixed", "Timber"],
    pressureLevel: "Low",
    elevationRange: [7500, 10000],
    publicLandPct: 0.90,
    tagQuotaNonresident: 20,
    notes: "Pure lottery. Trophy quality. Apply every year for a chance.",
    nearestAirport: "ABQ (2.5 hrs) or SAF (1.5 hrs)",
    driveTimeFromAirport: "2.5 hours from ABQ, 1.5 hours from Santa Fe",
    tacticalNotes: {
      accessMethod: "Valles Caldera National Preserve has managed access. Check-in required. Some areas vehicle-accessible, others hike-in only. Well-organized hunt program.",
      glassingStrategy: "Glass the vast caldera meadows — open grasslands surrounded by pine/aspen. Bulls are visible at extreme distances. Set up on caldera rim and glass into the bowl.",
      campingOptions: "Limited camping within the preserve — check regulations. Los Alamos and Jemez Springs have lodging. Santa Fe is 1.5 hrs away.",
      bestSeasonTier: "1st Rifle (Oct) / 2nd Rifle (Nov)",
      bestArrivalDate: "Oct 13 for 1st Rifle",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "320-370 class bulls. Valles Caldera produces world-class elk. The managed preserve format means low pressure and healthy herds. This is a dream draw.",
      proTip: "Pure lottery. No points. Apply every single year for $12. If you ever draw Unit 34, clear your calendar — this is one of the premier elk hunts in North America. Some hunters apply their entire lives hoping for this tag.",
    },
  },

  // ============================================================================
  // Oregon Elk
  // ============================================================================
  {
    id: "or-elk-starkey",
    stateId: "OR",
    speciesId: "elk",
    unitCode: "Starkey",
    unitName: "Starkey",
    successRate: 0.25,
    trophyRating: 6,
    pointsRequiredResident: 1,
    pointsRequiredNonresident: 3,
    terrainType: ["Timber", "Mixed"],
    pressureLevel: "Moderate",
    elevationRange: [4000, 7500],
    publicLandPct: 0.60,
    tagQuotaNonresident: 45,
    nearestAirport: "PDX (5 hrs) or RDM (3 hrs)",
    driveTimeFromAirport: "5 hours from Portland, 3 hours from Redmond",
    tacticalNotes: {
      accessMethod: "NF road access. Mix of timber roads and trailheads. Moderate terrain compared to mountain states. 4WD helpful.",
      glassingStrategy: "Glass meadow edges and clearcut regeneration areas. OR elk use logged areas and meadow systems. Less open than WY/NV — more timber-focused hunting.",
      campingOptions: "Wallowa-Whitman NF campgrounds and dispersed camping. Small-town services in La Grande and Enterprise.",
      bestSeasonTier: "Controlled Hunt (Oct)",
      bestArrivalDate: "Oct 1",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "260-300 class bulls. Eastern OR Rocky Mountain elk are quality animals. Not quite CO/WY caliber but excellent for the $8 application cost.",
      proTip: "OR's late application deadline (May) is strategically valuable — you'll know your CO, WY, and AZ draw results before you need to apply. Use OR as your backup plan: if you drew elsewhere, skip it; if you struck out everywhere, apply and build points.",
    },
  },

  // ============================================================================
  // Kansas Mule Deer
  // ============================================================================
  {
    id: "ks-md-001",
    stateId: "KS",
    speciesId: "mule_deer",
    unitCode: "1",
    unitName: "Western Kansas",
    successRate: 0.55,
    trophyRating: 6,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 2,
    terrainType: ["Prairie", "Mixed"],
    pressureLevel: "Low",
    elevationRange: [3000, 4500],
    publicLandPct: 0.15,
    tagQuotaNonresident: 100,
    notes: "NR preference points for deer. Agricultural terrain.",
    nearestAirport: "GCK (Garden City, 30 min) or MCI (5 hrs)",
    driveTimeFromAirport: "30 minutes from Garden City, 5 hours from KC",
    tacticalNotes: {
      accessMethod: "Mix of Walk-In Hunting Areas (WIHA) and private land access. WIHA areas are free public access. Build relationships with landowners for private land permission.",
      glassingStrategy: "Glass agricultural field edges, CRP grassland, and river breaks. Mule deer in western KS live in agricultural terrain — very different from mountain hunting. Glass from vehicle along section roads.",
      campingOptions: "Limited public camping. Motels in Garden City, Dodge City, Liberal. Budget accommodation available.",
      bestSeasonTier: "Rifle (Nov 29 - Dec 10)",
      bestArrivalDate: "Nov 28",
      typicalHuntLength: "5 days",
      trophyExpectation: "150-170 class bucks. Agricultural mule deer — different character than mountain deer. Heavy-bodied, well-fed animals. WIHA areas hold good deer.",
      proTip: "WIHA (Walk-In Hunting Areas) are Kansas's version of public access — free to hunt, marked with signs. Download the WIHA map from KDWPT. Some WIHA tracts hold excellent mule deer that get very little pressure.",
    },
  },

  // ============================================================================
  // Kansas Whitetail
  // ============================================================================
  {
    id: "ks-wt-general",
    stateId: "KS",
    speciesId: "whitetail",
    unitCode: "General",
    unitName: "Statewide Whitetail",
    successRate: 0.60,
    trophyRating: 8,
    pointsRequiredResident: 0,
    pointsRequiredNonresident: 1,
    terrainType: ["Prairie", "Mixed"],
    pressureLevel: "Moderate",
    elevationRange: [1000, 3000],
    publicLandPct: 0.10,
    tagQuotaNonresident: 500,
    notes: "Premier whitetail destination. NR draw with preference points. Rut hunting Nov-Dec is prime.",
    nearestAirport: "MCI (Kansas City, 2-3 hrs) or ICT (Wichita, 1-2 hrs)",
    driveTimeFromAirport: "2-3 hours from KC to prime whitetail areas",
    tacticalNotes: {
      accessMethod: "Mostly private land — outfitter leases, WIHA areas, or cultivate landowner relationships. Limited public land but WIHA is the NR's best bet for DIY access.",
      glassingStrategy: "Not a glassing hunt — stand/blind hunting over food plots, travel corridors, and scrape lines is primary tactic. Scout for sign pre-season. November rut is all about sitting high-traffic corridors.",
      campingOptions: "Motels and farm stays. Limited camping. Most NR hunters use outfitters or book lodging in small towns.",
      bestSeasonTier: "Peak Rut (Nov 5-20) / Archery (Sep-Dec)",
      bestArrivalDate: "Nov 8 for peak rut",
      typicalHuntLength: "5-7 days",
      trophyExpectation: "140-170+ class bucks. Kansas is one of the top 5 whitetail states in the US. NR preference points mean you can time your hunt for peak rut. Eastern KS river bottoms produce giants.",
      proTip: "Kansas whitetail is the diversification play in a western portfolio. When elk hunts are done for the year, a late-November KS whitetail trip is perfect. Build 1 preference point, draw year 2, and hunt the rut.",
    },
  },
];
