import { State } from "@/lib/types";

export const STATES: State[] = [
  {
    id: "CO",
    name: "Colorado",
    abbreviation: "CO",
    pointSystem: "preference",
    pointSystemDetails: {
      preferencePct: 80,
      randomPct: 20,
      description: "True Preference with 80/20 hybrid. Tags go to highest point holders first.",
    },
    fgUrl: "https://cpw.state.co.us",
    buyPointsUrl: "https://cpw.state.co.us/activities/hunting/big-game/primary-draw",
    applicationDeadlines: {
      elk: { open: "2026-03-01", close: "2026-04-07" },
      mule_deer: { open: "2026-03-01", close: "2026-04-07" },
      black_bear: { open: "2026-03-01", close: "2026-04-07" },
      moose: { open: "2026-03-01", close: "2026-04-07" },
      pronghorn: { open: "2026-03-01", close: "2026-04-07" },
      bighorn_sheep: { open: "2026-03-01", close: "2026-04-07" },
      mountain_goat: { open: "2026-03-01", close: "2026-04-07" },
      mountain_lion: { open: "2026-03-01", close: "2026-04-07" },
    },
    deadlineTimezone: "America/Denver",
    onceInALifetime: ["moose", "bighorn_sheep", "mountain_goat"],
    licenseFees: { qualifyingLicense: 101.54, appFee: 11, pointFee: 0 },
    feeSchedule: [
      { name: "NR Qualifying License", amount: 101.54, frequency: "annual", required: true, notes: "Required before applying. One-time annual purchase covers all species." },
      { name: "Application Processing Fee", amount: 11, frequency: "per_species", required: true, notes: "Per application per species. Non-refundable." },
      { name: "Habitat Stamp", amount: 12.47, frequency: "annual", required: true, notes: "Required for all hunters age 18+." },
      { name: "Preference Point (Moose/Sheep/Goat)", amount: 100, frequency: "per_species", required: false, notes: "Elk/deer/pronghorn/bear points are free with application." },
    ],
    residentLicenseFees: { qualifyingLicense: 0, appFee: 8, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Habitat Stamp", amount: 12.47, frequency: "annual", required: true, notes: "Required for all hunters age 18-64." },
      { name: "Application Processing Fee", amount: 8, frequency: "per_species", required: true, notes: "Per species application. Non-refundable." },
      { name: "Preference Point (Moose/Sheep/Goat)", amount: 50, frequency: "per_species", required: false, notes: "Only for moose, bighorn sheep, mountain goat. Elk/deer/pronghorn points are free." },
    ],
    residentPointCost: { elk: 0, mule_deer: 0, black_bear: 0, moose: 50, pronghorn: 0, bighorn_sheep: 50, mountain_goat: 50, mountain_lion: 0 },
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit. You list a first choice and second choice hunt code. Point-only strategy: pick point-only as first choice, actual hunt code as second.",
    applicationTips: [
      "Use the 2nd-choice tactic: list point-only as 1st choice, real unit as 2nd choice. You build a point AND get a shot at drawing.",
      "Qualifying license must be purchased before the draw — even if you're only buying points.",
      "OTC elk tags are available if you strike out in the draw. Over-the-counter 2nd/3rd rifle is always a backup.",
      "Moose, goat, and sheep are once-in-a-lifetime species in CO.",
    ],
    availableSpecies: ["elk", "mule_deer", "black_bear", "moose", "pronghorn", "bighorn_sheep", "mountain_goat", "mountain_lion"],
    drawResultDates: { elk: "2026-06-01", mule_deer: "2026-06-01", black_bear: "2026-06-01", moose: "2026-06-01", pronghorn: "2026-06-01", bighorn_sheep: "2026-06-01", mountain_goat: "2026-06-01", mountain_lion: "2026-06-01" },
    pointCost: { elk: 0, mule_deer: 0, black_bear: 0, moose: 100, pronghorn: 0, bighorn_sheep: 100, mountain_goat: 100, mountain_lion: 0 },
    tagCosts: { elk: 825.03, mule_deer: 494.47, black_bear: 294.75, moose: 2758.49, pronghorn: 494.47, bighorn_sheep: 2758.49, mountain_goat: 2758.49, mountain_lion: 825.03 },
    residentTagCosts: { elk: 67.86, mule_deer: 49.15, black_bear: 61.62, moose: 375.97, pronghorn: 49.15, bighorn_sheep: 375.97, mountain_goat: 375.97, mountain_lion: 61.62 },
    color: "#1E40AF",
    lastScrapedAt: "2026-02-20",
    sourceUrl: "https://cpw.state.co.us/activities/hunting/big-game",
    dataVersion: "2026.1",
    logistics: {
      primaryAirport: "DEN (Denver International)",
      secondaryAirports: ["GJT (Grand Junction)", "EGE (Eagle/Vail)", "HDN (Hayden/Steamboat)"],
      rentalCarNotes: "4WD SUV mandatory for NW Colorado forest roads — reserve early for September-November. Enterprise and National at DEN have best selection. Turo is a backup option for lifted trucks.",
      meatProcessing: "Ship quartered elk via FedEx cold pack from Craig or Meeker — $150-250 per animal. Local processors: Craig Custom Meats, Meeker Locker, Valley Meat Co (Rifle). Call ahead to schedule during rifle seasons.",
      drivingNotes: "DEN to NW CO units (3, 4, 11, 211): 3-4 hrs via I-70 W → Hwy 13 N. GJT to Unit 4/11 is ~2 hrs. HDN (Steamboat) is closest to Units 4/14 area.",
    },
    pointOnlyApplication: {
      instructions: "On the CPW online portal, select 'Preference Point Only' (code PP001) as your 1st choice hunt code. This builds a preference point with zero risk of drawing a tag.",
      huntCode: "PP001",
      secondChoiceTactic: "List PP001 as 1st choice, then your actual unit hunt code as 2nd choice. You earn a preference point AND enter the random pool for your 2nd-choice unit. Best of both worlds.",
      purchaseUrl: "https://cpw.state.co.us/activities/hunting/big-game/primary-draw",
      deadline: "April 7, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 2-30", notes: "Elk bugling season. Backcountry hunters thrive. Warm days, cold nights at 8,000+ ft.", bestFor: "backpack" },
      { tier: "Muzzleloader", dates: "Sep 12-22", notes: "Transition period. Elk still vocal but harder to pattern. Lower pressure than archery.", bestFor: "any" },
      { tier: "1st Rifle", dates: "Oct 14-18", notes: "5-day season. Heavy opening-morning pressure. Best for well-scouted locals and dedicated NR hunters.", bestFor: "any" },
      { tier: "2nd Rifle", dates: "Oct 22-30", notes: "Sweet spot for truck-camp hunters. Less pressure, elk transitioning to lower elevations. 9 days to hunt.", bestFor: "truck_camp" },
      { tier: "3rd Rifle", dates: "Nov 5-13", notes: "Mule deer rut begins. Cold weather pushes elk to winter range. Prime for glassing sage-to-timber transitions.", bestFor: "truck_camp" },
      { tier: "4th Rifle", dates: "Nov 17-21", notes: "Late season. Deep snow possible. Migration corridors are key. Dress warm, glass far.", bestFor: "truck_camp" },
    ],
    statePersonality: "Colorado is the workhorse of your portfolio. The preference point system is the most predictable in the West — you know exactly when you'll draw. The second-choice tactic is your secret weapon: build a point AND hunt every year. NW Colorado units (3, 4, 11, 211) are truck-friendly with high road density and strong public land access. OTC backup tags mean you can always go hunting even if you don't draw. At ~$151/year for elk points, it's one of the most capital-efficient investments in western hunting.",
  },
  {
    id: "WY",
    name: "Wyoming",
    abbreviation: "WY",
    pointSystem: "hybrid",
    pointSystemDetails: {
      preferencePct: 75,
      randomPct: 25,
      description: "75% of tags to highest points, 25% random draw.",
    },
    fgUrl: "https://wgfd.wyo.gov",
    buyPointsUrl: "https://wgfd.wyo.gov/hunting-trapping/preference-points",
    applicationDeadlines: {
      elk: { open: "2026-01-02", close: "2026-03-15" },
      mule_deer: { open: "2026-01-02", close: "2026-03-15" },
      moose: { open: "2026-01-02", close: "2026-03-15" },
      black_bear: { open: "2026-01-02", close: "2026-03-15" },
      grizzly: { open: "2026-01-02", close: "2026-03-15" },
      pronghorn: { open: "2026-01-02", close: "2026-03-15" },
      bighorn_sheep: { open: "2026-01-02", close: "2026-03-15" },
      mountain_goat: { open: "2026-01-02", close: "2026-03-15" },
      bison: { open: "2026-01-02", close: "2026-03-15" },
      mountain_lion: { open: "2026-01-02", close: "2026-03-15" },
      wolf: { open: "2026-01-02", close: "2026-03-15" },
    },
    deadlineTimezone: "America/Denver",
    onceInALifetime: ["moose", "bighorn_sheep", "mountain_goat", "bison"],
    licenseFees: { qualifyingLicense: 0, appFee: 15, pointFee: 0 },
    feeSchedule: [
      { name: "NR Application Fee", amount: 15, frequency: "per_species", required: true, notes: "Non-refundable application fee per species." },
      { name: "NR Preference Point (varies)", amount: 52, frequency: "per_species", required: false, notes: "Elk $52, Deer $41, Pronghorn $31, Moose/Sheep $150. No points for bear, lion, wolf, bison, goat." },
    ],
    residentLicenseFees: { qualifyingLicense: 0, appFee: 5, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Application Fee", amount: 5, frequency: "per_species", required: true, notes: "Resident application fee per species." },
      { name: "Conservation Stamp", amount: 21.50, frequency: "annual", required: true, notes: "Required if drawn." },
    ],
    residentPointCost: { elk: 0, mule_deer: 0, black_bear: 0, grizzly: 0, moose: 7, pronghorn: 0, bighorn_sheep: 7, mountain_goat: 7, bison: 0, mountain_lion: 0, wolf: 0 },
    applicationApproach: "per_region",
    applicationApproachDescription: "Apply by hunt area (region-based). Elk areas are grouped: Western, Southern, Eastern. Each area has different point creep.",
    applicationTips: [
      "WY is region-based for elk. Research which hunt areas fall in your target region before applying.",
      "Special tags (moose, sheep, goat) are separate draws with their own preference points.",
      "No qualifying license required to buy points — just the point fee.",
      "Point creep is real: popular areas like 100 (desert elk) are 5+ year investments.",
    ],
    availableSpecies: ["elk", "mule_deer", "black_bear", "grizzly", "moose", "pronghorn", "bighorn_sheep", "mountain_goat", "bison", "mountain_lion", "wolf"],
    drawResultDates: { elk: "2026-05-15", mule_deer: "2026-05-15", moose: "2026-05-15", black_bear: "2026-05-15", grizzly: "2026-05-15", pronghorn: "2026-05-15", bighorn_sheep: "2026-05-15", mountain_goat: "2026-05-15", bison: "2026-05-15", mountain_lion: "2026-05-15", wolf: "2026-05-15" },
    pointCost: { elk: 52, mule_deer: 41, black_bear: 0, grizzly: 0, moose: 150, pronghorn: 31, bighorn_sheep: 150, mountain_goat: 0, bison: 0, mountain_lion: 0, wolf: 0 },
    tagCosts: { elk: 692, mule_deer: 374, black_bear: 373, grizzly: 0, moose: 2752, pronghorn: 326, bighorn_sheep: 3002, mountain_goat: 2752, bison: 6002, mountain_lion: 373, wolf: 187 },
    residentTagCosts: { elk: 57, mule_deer: 42, black_bear: 47, grizzly: 0, moose: 152, pronghorn: 37, bighorn_sheep: 152, mountain_goat: 152, bison: 414, mountain_lion: 32, wolf: 21 },
    color: "#92400E",
    lastScrapedAt: "2026-02-20",
    sourceUrl: "https://wgfd.wyo.gov/hunting-trapping",
    dataVersion: "2026.1",
    logistics: {
      primaryAirport: "JAC (Jackson Hole) or SLC (Salt Lake City)",
      secondaryAirports: ["CPR (Casper)", "SHR (Sheridan)", "BIL (Billings, MT — drive south)"],
      rentalCarNotes: "4WD is essential everywhere in WY. Rent at SLC or JAC — SLC has better prices and availability. Expect 3-5 hour drives from airport to most hunt areas. Gas stations are sparse; fill up at every opportunity.",
      meatProcessing: "Processors in Cody, Sheridan, and Lander. Ship FedEx cold pack from closest town — $200-300 for elk. Wyoming Meat Co (Cody) does full processing + shipping.",
      drivingNotes: "JAC to western elk areas: 1-3 hrs. SLC to western WY: 4-5 hrs via I-80 or US-89. Casper is central to many hunt areas. Long drives are part of WY hunting.",
    },
    pointOnlyApplication: {
      instructions: "On the WY Game & Fish portal, purchase a 'Preference Point Only' for your species. No qualifying license required. Just the point fee ($55) + app fee ($15) = $70/species.",
      huntCode: "Preference Point Only",
      purchaseUrl: "https://wgfd.wyo.gov/hunting-trapping/preference-points",
      deadline: "March 15, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 1-30", notes: "Bugling season. Backcountry access to wilderness areas. Best trophy potential.", bestFor: "backpack" },
      { tier: "General Rifle", dates: "Oct 1-31", notes: "Month-long season in most areas. Mix of pressure levels depending on area access.", bestFor: "any" },
      { tier: "Late Season", dates: "Nov 1-15", notes: "Cold weather hunts. Migration corridors key. Desert elk units peak in November.", bestFor: "truck_camp" },
    ],
    statePersonality: "Wyoming is your quality play. The 75/25 hybrid system rewards patience with a clear preference path, but still gives you a random-pool shot every year. Desert elk hunts (Area 100) are legendary — 80-90% success on mature bulls in sagebrush country, perfect for truck-camp glassers. The Bighorns offer classic timber elk with no grizzly pressure. Mule deer in the Wyoming Range are world-class during the late rut. WY requires longer drives and more logistical planning, but the payoff in animal quality per dollar is hard to beat.",
  },
  {
    id: "MT",
    name: "Montana",
    abbreviation: "MT",
    pointSystem: "dual",
    pointSystemDetails: {
      preferencePct: 75,
      randomPct: 25,
      squared: true,
      description: "Preference points for combo license (75/25). Bonus points (squared) for special permits.",
    },
    fgUrl: "https://fwp.mt.gov",
    buyPointsUrl: "https://fwp.mt.gov/buyandapply",
    applicationDeadlines: {
      elk: { open: "2026-03-01", close: "2026-04-01" },
      mule_deer: { open: "2026-03-01", close: "2026-04-01" },
      black_bear: { open: "2026-03-01", close: "2026-04-01" },
      moose: { open: "2026-03-01", close: "2026-06-01" },
      grizzly: { open: "2026-03-01", close: "2026-06-01" },
      whitetail: { open: "2026-03-01", close: "2026-04-01" },
      pronghorn: { open: "2026-03-01", close: "2026-04-01" },
      bighorn_sheep: { open: "2026-03-01", close: "2026-06-01" },
      mountain_goat: { open: "2026-03-01", close: "2026-06-01" },
      bison: { open: "2026-03-01", close: "2026-06-01" },
      mountain_lion: { open: "2026-03-01", close: "2026-04-01" },
      wolf: { open: "2026-03-01", close: "2026-04-01" },
    },
    deadlineTimezone: "America/Denver",
    onceInALifetime: ["moose", "bighorn_sheep", "mountain_goat", "bison"],
    licenseFees: { qualifyingLicense: 0, appFee: 5, pointFee: 100 },
    feeSchedule: [
      { name: "NR Combo License Application", amount: 5, frequency: "annual", required: true, notes: "Non-refundable application fee for Big Game Combo." },
      { name: "NR Big Game Combo License", amount: 1312, frequency: "annual", required: true, notes: "Full combo license if drawn. Includes elk, deer, fishing, bird." },
      { name: "Preference Point", amount: 100, frequency: "annual", required: false, notes: "Purchase to build preference points for combo license draw. Max 2 consecutive years without applying." },
      { name: "Special Permit App (Moose/Sheep/Goat/Bison)", amount: 50, frequency: "per_species", required: false, notes: "Non-refundable application fee for special species." },
    ],
    residentLicenseFees: { qualifyingLicense: 10, appFee: 5, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Base Hunting License", amount: 10, frequency: "annual", required: true, notes: "Required. Conservation license ($8) also required separately." },
      { name: "Application Fee", amount: 5, frequency: "per_species", required: true, notes: "Non-refundable. $10 for moose/sheep/goat/bison." },
      { name: "Deer Tag", amount: 16, frequency: "per_species", required: false, notes: "General deer tag." },
      { name: "Elk Tag", amount: 20, frequency: "per_species", required: false, notes: "General elk tag." },
      { name: "Sportsman License", amount: 64.50, frequency: "annual", required: false, notes: "Includes elk, deer, fishing, upland bird. Best value." },
    ],
    residentPointCost: { elk: 5, mule_deer: 5, black_bear: 5, grizzly: 10, moose: 10, whitetail: 5, pronghorn: 5, bighorn_sheep: 10, mountain_goat: 10, bison: 10, mountain_lion: 5, wolf: 5 },
    applicationApproach: "per_state",
    applicationApproachDescription: "Apply for a statewide combo license. If drawn, you get elk + deer tags. District selection happens after draw results.",
    applicationTips: [
      "The combo license is an all-in deal: one application for elk + deer. Great value if drawn.",
      "Special permits (moose, sheep, goat, bear) are separate applications with bonus points (squared).",
      "NR combo license quota is limited — apply every year to build preference points.",
      "B-tags (cow elk) are often available OTC after the draw for additional opportunity.",
    ],
    availableSpecies: ["elk", "mule_deer", "black_bear", "grizzly", "moose", "whitetail", "pronghorn", "bighorn_sheep", "mountain_goat", "bison", "mountain_lion", "wolf"],
    drawResultDates: { elk: "2026-06-15", mule_deer: "2026-06-15", black_bear: "2026-06-15", moose: "2026-07-01", grizzly: "2026-07-01", whitetail: "2026-06-15", pronghorn: "2026-06-15", bighorn_sheep: "2026-07-01", mountain_goat: "2026-07-01", bison: "2026-07-01", mountain_lion: "2026-06-15", wolf: "2026-06-15" },
    pointCost: { elk: 100, mule_deer: 100, black_bear: 5, grizzly: 50, moose: 50, whitetail: 100, pronghorn: 100, bighorn_sheep: 50, mountain_goat: 50, bison: 50, mountain_lion: 5, wolf: 5 },
    tagCosts: { elk: 1312, mule_deer: 1312, black_bear: 350, grizzly: 1000, moose: 1250, whitetail: 1312, pronghorn: 205, bighorn_sheep: 1250, mountain_goat: 1250, bison: 1250, mountain_lion: 320, wolf: 50 },
    residentTagCosts: { elk: 20, mule_deer: 16, black_bear: 19, grizzly: 50, moose: 125, whitetail: 16, pronghorn: 16, bighorn_sheep: 125, mountain_goat: 125, bison: 125, mountain_lion: 19, wolf: 12 },
    color: "#065F46",
    lastScrapedAt: "2026-02-20",
    sourceUrl: "https://fwp.mt.gov/hunting",
    dataVersion: "2026.1",
    logistics: {
      primaryAirport: "BZN (Bozeman Yellowstone)",
      secondaryAirports: ["BIL (Billings)", "MSO (Missoula)", "GTF (Great Falls)"],
      rentalCarNotes: "4WD required for most hunting areas. BZN and BIL have best rental selection. Reserve early for October-November — rentals sell out during hunting season. Chains or good snow tires recommended for late season.",
      meatProcessing: "Processors throughout MT. Montana Meats (Bozeman), Yellowstone Meats (Billings). Most processors ship. Budget $200-350 for elk processing + shipping.",
      drivingNotes: "BZN to SW MT hunting: 1-2 hrs. BIL to eastern MT: 2-4 hrs. Montana is huge — plan your airport based on hunt area. MSO for western MT, GTF for Rocky Mountain Front.",
    },
    pointOnlyApplication: {
      instructions: "Apply for the NR Big Game Combo through FWP portal. If not drawn, you automatically receive a preference point. Application fee ($50) is your point investment.",
      purchaseUrl: "https://fwp.mt.gov/buyandapply",
      deadline: "April 1, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 2 - Oct 13", notes: "Long season. Elk bugling, backcountry access. Lower pressure than rifle.", bestFor: "backpack" },
      { tier: "General Rifle", dates: "Oct 22 - Nov 26", notes: "5+ week season. Opening week pressure, then thins out. Snow helps movement.", bestFor: "any" },
      { tier: "Whitetail Rut", dates: "Nov 10-25", notes: "Peak whitetail rut in river bottoms and coulees. Combo license includes a whitetail tag.", bestFor: "truck_camp" },
    ],
    statePersonality: "Montana is the best value in western hunting. One combo license gives you elk, deer, and whitetail — three hunts for the price of one. The preference point system means you'll draw every 2-3 years with discipline. Montana has massive public land, diverse terrain from prairie coulees to alpine basins, and the general season is 5+ weeks long. The catch: NR combo licenses are limited, so building preference points is essential. Spring bear is OTC and an excellent add-on trip. Montana rewards the persistent hunter who applies every year.",
  },
  {
    id: "NV",
    name: "Nevada",
    abbreviation: "NV",
    pointSystem: "bonus_squared",
    pointSystemDetails: {
      squared: true,
      description: "Bonus point system with squared weighting. (Points+1)^2 chances in draw.",
    },
    fgUrl: "https://www.ndow.org",
    buyPointsUrl: "https://www.ndow.org/apply-buy/apply-buy-hunting/",
    applicationDeadlines: {
      elk: { open: "2026-03-10", close: "2026-04-14" },
      mule_deer: { open: "2026-03-10", close: "2026-04-14" },
      pronghorn: { open: "2026-03-10", close: "2026-04-14" },
      bighorn_sheep: { open: "2026-03-10", close: "2026-04-14" },
      mountain_lion: { open: "2026-03-10", close: "2026-04-14" },
    },
    deadlineTimezone: "America/Los_Angeles",
    onceInALifetime: ["bighorn_sheep"],
    licenseFees: { qualifyingLicense: 155, appFee: 14, pointFee: 0 },
    feeSchedule: [
      { name: "NR Combination Hunting License", amount: 155, frequency: "annual", required: true, notes: "Required before applying. Your license IS your point entry." },
      { name: "Tag Application Fee", amount: 14, frequency: "per_species", required: true, notes: "Per species. Elk is $19 (includes $5 elk mgmt fee)." },
    ],
    residentLicenseFees: { qualifyingLicense: 38, appFee: 14, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Hunting License", amount: 38, frequency: "annual", required: true, notes: "Required before applying. License IS your point entry." },
      { name: "Tag Application Fee", amount: 14, frequency: "per_species", required: true, notes: "Per species. Elk is $19 (includes $5 elk mgmt fee)." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit with up to 5 choices ranked. Bonus squared system rewards patience — your odds improve exponentially with points.",
    applicationTips: [
      "Your hunting license IS your point entry — buying the license alone earns a bonus point if you don't draw.",
      "Squared bonus means 5 points = 36 chances vs 1 chance for a zero-point applicant. Patience pays off big.",
      "List 5 choices per species — don't leave choices blank, it costs you nothing.",
      "Trophy quality is exceptional. Most NV hunts are once-in-a-lifetime experiences.",
    ],
    availableSpecies: ["elk", "mule_deer", "pronghorn", "bighorn_sheep", "mountain_lion"],
    drawResultDates: { elk: "2026-06-01", mule_deer: "2026-06-01", pronghorn: "2026-06-01", bighorn_sheep: "2026-06-01", mountain_lion: "2026-06-01" },
    pointCost: { elk: 0, mule_deer: 0, pronghorn: 0, bighorn_sheep: 0, mountain_lion: 0 },
    tagCosts: { elk: 1200, mule_deer: 240, pronghorn: 300, bighorn_sheep: 1200, mountain_lion: 104 },
    residentTagCosts: { elk: 120, mule_deer: 30, pronghorn: 60, bighorn_sheep: 120, mountain_lion: 29 },
    color: "#7C3AED",
    lastScrapedAt: "2026-02-20",
    sourceUrl: "https://www.ndow.org/hunt",
    dataVersion: "2026.1",
    logistics: {
      primaryAirport: "RNO (Reno-Tahoe International)",
      secondaryAirports: ["LAS (Las Vegas)", "EKO (Elko)"],
      rentalCarNotes: "4WD strongly recommended. High-clearance SUV ideal for remote NV roads. RNO has best selection for northern units. LAS works for southern units. Carry extra water and fuel — services are sparse.",
      meatProcessing: "Limited processors in rural NV. Elko Custom Meats, Winnemucca Locker. Plan to quarter and ice the animal yourself and drive to a processor. Ship from Elko or Reno FedEx.",
      drivingNotes: "RNO to Jarbidge area: 4-5 hrs via I-80 E → Hwy 225 N. NV units require long drives on remote roads. Bring a spare tire and recovery gear. Cell service extremely limited.",
    },
    pointOnlyApplication: {
      instructions: "Buy your NV hunting license ($142) through NDOW portal. This alone earns you a bonus point. Add the $15 application fee per species to also enter the draw. Your license IS your point investment.",
      purchaseUrl: "https://www.ndow.org/hunt/apply-for-a-tag/",
      deadline: "April 14, 2026",
    },
    seasonTiers: [
      { tier: "Early Rifle", dates: "Sep 10-25", notes: "Warm weather, elk still in summer patterns. Higher elevations.", bestFor: "backpack" },
      { tier: "Late Rifle", dates: "Oct 10 - Nov 15", notes: "Cooler temps. Mule deer rut. Animals moving to winter range. Prime glassing conditions.", bestFor: "truck_camp" },
    ],
    statePersonality: "Nevada is your long-term trophy investment. The bonus-squared system means your odds improve exponentially — 5 points gives you 36x the chances of a first-time applicant. Nevada produces some of the largest mule deer and elk in the West, but tags are extremely limited. This is a patience play: invest $157/year (license + app fee) and let the math compound. When you finally draw, expect a hunt of a lifetime with near-trophy-class animals. NV is remote, harsh, and wild — exactly what makes it special.",
  },
  {
    id: "AZ",
    name: "Arizona",
    abbreviation: "AZ",
    pointSystem: "bonus",
    pointSystemDetails: {
      squared: false,
      description: "Bonus point system (not squared). Each point = 1 additional chance.",
    },
    fgUrl: "https://www.azgfd.com",
    buyPointsUrl: "https://www.azgfd.com/hunting/draw/",
    applicationDeadlines: {
      elk: { open: "2026-02-11", close: "2026-03-11" },
      mule_deer: { open: "2026-02-11", close: "2026-03-11" },
      coues_deer: { open: "2026-02-11", close: "2026-03-11" },
      black_bear: { open: "2026-06-03", close: "2026-07-08" },
      pronghorn: { open: "2026-02-11", close: "2026-03-11" },
      bighorn_sheep: { open: "2026-02-11", close: "2026-03-11" },
      bison: { open: "2026-02-11", close: "2026-03-11" },
      mountain_lion: { open: "2026-06-03", close: "2026-07-08" },
    },
    deadlineTimezone: "America/Phoenix",
    onceInALifetime: ["bighorn_sheep", "bison"],
    licenseFees: { qualifyingLicense: 160, appFee: 15, pointFee: 0 },
    feeSchedule: [
      { name: "NR Hunting License", amount: 160, frequency: "annual", required: true, notes: "Required before applying. Also serves as your point entry." },
      { name: "Application Fee", amount: 15, frequency: "per_species", required: true, notes: "Per species application fee." },
    ],
    residentLicenseFees: { qualifyingLicense: 37, appFee: 13, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Hunting License", amount: 37, frequency: "annual", required: true, notes: "Required before applying. Also serves as your point entry." },
      { name: "Application Fee", amount: 13, frequency: "per_species", required: true, notes: "Per species application fee. Includes bonus point." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit with up to 5 choices. Bonus point system (not squared) — linear odds improvement.",
    applicationTips: [
      "License IS your point entry — buy even if not applying to earn a bonus point.",
      "AZ bonus points are NOT squared, so the advantage builds linearly. Less dramatic than NV.",
      "Elk quality is exceptional — AZ bulls average larger than most western states.",
      "Spring bear hunts are a separate draw with their own deadline.",
    ],
    availableSpecies: ["elk", "mule_deer", "coues_deer", "black_bear", "pronghorn", "bighorn_sheep", "bison", "mountain_lion"],
    drawResultDates: { elk: "2026-04-30", mule_deer: "2026-04-30", black_bear: "2026-08-01", coues_deer: "2026-04-30", pronghorn: "2026-04-30", bighorn_sheep: "2026-04-30", bison: "2026-04-30", mountain_lion: "2026-04-30" },
    pointCost: { elk: 15, mule_deer: 15, coues_deer: 15, black_bear: 15, pronghorn: 15, bighorn_sheep: 15, bison: 15, mountain_lion: 15 },
    tagCosts: { elk: 665, mule_deer: 315, coues_deer: 315, black_bear: 165, pronghorn: 565, bighorn_sheep: 1815, bison: 5415, mountain_lion: 75 },
    residentTagCosts: { elk: 148, mule_deer: 58, coues_deer: 58, black_bear: 38, pronghorn: 103, bighorn_sheep: 313, bison: 1113, mountain_lion: 15 },
    color: "#DC2626",
    lastScrapedAt: "2026-02-20",
    sourceUrl: "https://www.azgfd.com/hunting/draw",
    dataVersion: "2026.1",
    logistics: {
      primaryAirport: "PHX (Phoenix Sky Harbor)",
      secondaryAirports: ["FLG (Flagstaff)", "TUS (Tucson)"],
      rentalCarNotes: "4WD helpful for forest roads but not always required. PHX has tons of rental options. FLG is closer to Kaibab and Rim Country units but limited rental selection. Roads are generally better maintained than other western states.",
      meatProcessing: "Flagstaff Meat Co, Payson Locker, Show Low Custom Meats. AZ has good processor coverage near hunting areas. Ship from FLG or PHX FedEx.",
      drivingNotes: "PHX to Kaibab (Unit 1): 4.5 hrs via I-17 N → I-40 W → Hwy 64. PHX to Rim Country: 2 hrs via Hwy 87. The drive from PHX to northern units is scenic but long.",
    },
    pointOnlyApplication: {
      instructions: "Buy your AZ hunting license ($160) through AZGFD portal. This earns a bonus point even if you don't apply. Add $15 app fee per species to also enter the draw.",
      purchaseUrl: "https://www.azgfd.com/hunting/draw/",
      deadline: "March 11, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 13 - Oct 2", notes: "Bull elk bugling in Rim Country. Warm days, cool nights. Pine forest hunting.", bestFor: "any" },
      { tier: "Early Rifle", dates: "Oct 17-22", notes: "Short season, high success in quality units. Animals still in early fall patterns.", bestFor: "any" },
      { tier: "Late Rifle", dates: "Nov 14-27", notes: "Rut season for elk. Cold mornings at elevation. Trophy bulls active.", bestFor: "truck_camp" },
      { tier: "Muzzleloader", dates: "Oct 3-16", notes: "Transition season. Good for patient hunters. Lower pressure.", bestFor: "any" },
    ],
    statePersonality: "Arizona is the sleeper trophy state. AZ bulls average larger body and antler size than nearly any other western state, and the limited tag allocation means low hunting pressure. The linear bonus point system is slower to compound than Nevada's squared system, but the hunt quality when you draw is exceptional. Kaibab (Unit 1) is legendary for both elk and mule deer. The Mogollon Rim offers accessible hunting with stunning scenery. AZ is worth the long-term point investment for the hunter who wants a genuine trophy experience.",
  },
  {
    id: "UT",
    name: "Utah",
    abbreviation: "UT",
    pointSystem: "dual",
    pointSystemDetails: {
      description: "Preference points for general season. Bonus points for limited-entry.",
    },
    fgUrl: "https://wildlife.utah.gov",
    buyPointsUrl: "https://wildlife.utah.gov/hunting-in-utah.html",
    applicationDeadlines: {
      elk: { open: "2026-01-30", close: "2026-03-05" },
      mule_deer: { open: "2026-01-30", close: "2026-03-05" },
      black_bear: { open: "2026-01-30", close: "2026-03-05" },
      moose: { open: "2026-01-30", close: "2026-03-05" },
      pronghorn: { open: "2026-01-30", close: "2026-03-05" },
      bighorn_sheep: { open: "2026-01-30", close: "2026-03-05" },
      mountain_goat: { open: "2026-01-30", close: "2026-03-05" },
      bison: { open: "2026-01-30", close: "2026-03-05" },
      mountain_lion: { open: "2026-01-30", close: "2026-03-05" },
    },
    deadlineTimezone: "America/Denver",
    onceInALifetime: ["moose", "bighorn_sheep", "mountain_goat", "bison"],
    licenseFees: { qualifyingLicense: 144, appFee: 21, pointFee: 0 },
    feeSchedule: [
      { name: "NR Hunting License", amount: 144, frequency: "annual", required: true, notes: "Required before applying. Effective July 1, 2025." },
      { name: "Application Fee", amount: 21, frequency: "per_species", required: true, notes: "Per species drawing application. Effective Sep 1, 2025." },
      { name: "NR General Elk Permit (if drawn)", amount: 849, frequency: "once", required: false, notes: "General-season bull elk. Includes 365-day fishing." },
      { name: "NR General Deer Permit (if drawn)", amount: 599, frequency: "once", required: false, notes: "General-season buck deer. Includes 365-day fishing." },
    ],
    residentLicenseFees: { qualifyingLicense: 40, appFee: 10, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Hunting License", amount: 40, frequency: "annual", required: true, notes: "Required before applying. Ages 18-64." },
      { name: "Application Fee", amount: 10, frequency: "per_species", required: true, notes: "Per species application." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit. Preference points for general season; bonus points for limited-entry and once-in-a-lifetime species.",
    applicationTips: [
      "Utah has TWO point systems: preference for general, bonus for limited-entry/OIAL.",
      "Moose, goat, bison are once-in-a-lifetime — you can only draw one ever.",
      "General season elk is easier to draw but high pressure. Limited-entry units are the trophy play.",
      "Application period is early (Jan-Mar) — don't miss the window.",
    ],
    availableSpecies: ["elk", "mule_deer", "black_bear", "moose", "pronghorn", "bighorn_sheep", "mountain_goat", "bison", "mountain_lion"],
    drawResultDates: { elk: "2026-05-15", mule_deer: "2026-05-15", black_bear: "2026-05-15", moose: "2026-05-15", pronghorn: "2026-05-15", bighorn_sheep: "2026-05-15", mountain_goat: "2026-05-15", bison: "2026-05-15", mountain_lion: "2026-05-15" },
    pointCost: { elk: 21, mule_deer: 21, black_bear: 21, moose: 21, pronghorn: 21, bighorn_sheep: 21, mountain_goat: 21, bison: 21, mountain_lion: 21 },
    tagCosts: { elk: 849, mule_deer: 599, black_bear: 600, moose: 3488, pronghorn: 571, bighorn_sheep: 3988, mountain_goat: 3488, bison: 4840, mountain_lion: 253 },
    residentTagCosts: { elk: 56, mule_deer: 46, black_bear: 93, moose: 454, pronghorn: 63, bighorn_sheep: 564, mountain_goat: 454, bison: 460, mountain_lion: 30 },
    color: "#B45309",
    lastScrapedAt: "2026-02-20",
    sourceUrl: "https://wildlife.utah.gov/hunting",
    dataVersion: "2026.1",
    logistics: {
      primaryAirport: "SLC (Salt Lake City International)",
      secondaryAirports: ["SGU (St. George)", "CDC (Cedar City)"],
      rentalCarNotes: "4WD recommended for backcountry units. SLC has excellent rental options. Good roads for most general-season areas. Southern UT desert units may need high clearance.",
      meatProcessing: "Utah has good processor coverage. Heber Valley Meats, Spanish Fork Locker, Cedar City Custom Meats. Most offer shipping. Budget $150-250 for elk.",
      drivingNotes: "SLC is centrally located. 1-2 hrs to most Wasatch units. 3-4 hrs to southern UT limited-entry areas. I-15 corridor makes north-south travel easy.",
    },
    pointOnlyApplication: {
      instructions: "Apply through UT DWR portal. Select your species and choose 'preference point only' option. License ($144) + app fee ($21) = $165/year total. Bonus points for limited-entry build separately.",
      purchaseUrl: "https://wildlife.utah.gov/hunting-in-utah.html",
      deadline: "March 5, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Aug 17 - Sep 12", notes: "Earliest opener in the West. Elk bugling. Hot days, cool mornings. High elevation.", bestFor: "backpack" },
      { tier: "Muzzleloader", dates: "Sep 25 - Oct 3", notes: "Short season. Elk transitioning to fall patterns. Lower pressure.", bestFor: "any" },
      { tier: "Any Weapon (General)", dates: "Oct 7-15", notes: "General season any-bull. High pressure on public land. Get deep or hunt smart.", bestFor: "any" },
      { tier: "Limited Entry Rifle", dates: "Oct 7-20", notes: "Trophy units. Low tag numbers = low pressure. Premium experience.", bestFor: "any" },
    ],
    statePersonality: "Utah is a dual-track state. General season elk is accessible but competitive — high pressure on public land means you need to hike deeper than others or scout better. The real value is in limited-entry units where preference and bonus points create a clear path to trophy-quality hunts. The early archery opener (mid-August) is unique and gives you a head start on the season. SLC airport makes logistics easy, and the state's diverse terrain — from Wasatch alpine to southern desert canyons — offers something for every hunting style. At $165/year (license + app fee), UT is a solid addition to any portfolio.",
  },
  {
    id: "NM",
    name: "New Mexico",
    abbreviation: "NM",
    pointSystem: "random",
    pointSystemDetails: {
      description: "Pure random lottery. No point system. Equal odds every year.",
    },
    fgUrl: "https://www.wildlife.state.nm.us",
    buyPointsUrl: "https://www.wildlife.state.nm.us/hunting/",
    applicationDeadlines: {
      elk: { open: "2026-03-18", close: "2026-04-22" },
      mule_deer: { open: "2026-03-18", close: "2026-04-22" },
      coues_deer: { open: "2026-03-18", close: "2026-04-22" },
      black_bear: { open: "2026-03-18", close: "2026-04-22" },
      pronghorn: { open: "2026-03-18", close: "2026-04-22" },
      bighorn_sheep: { open: "2026-03-18", close: "2026-04-22" },
      mountain_lion: { open: "2026-03-18", close: "2026-04-22" },
    },
    deadlineTimezone: "America/Denver",
    licenseFees: { qualifyingLicense: 65, appFee: 13, pointFee: 0 },
    feeSchedule: [
      { name: "NR Game-Hunting License", amount: 65, frequency: "annual", required: true, notes: "Required to hunt if drawn. Refunded if unsuccessful in draw." },
      { name: "NR Application Fee", amount: 13, frequency: "per_species", required: true, notes: "Non-refundable per species application fee." },
      { name: "HMAV", amount: 4, frequency: "annual", required: true, notes: "Habitat Management and Access Validation." },
      { name: "NR Elk Tag (if drawn)", amount: 548, frequency: "once", required: false, notes: "Standard elk tag — mature bull or either-sex." },
      { name: "NR Deer Tag (if drawn)", amount: 283, frequency: "once", required: false, notes: "Standard deer tag." },
    ],
    residentLicenseFees: { qualifyingLicense: 15, appFee: 7, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Game-Hunting License", amount: 15, frequency: "annual", required: true, notes: "Required before applying for draw hunts." },
      { name: "HMAV", amount: 4, frequency: "annual", required: true, notes: "Habitat Management and Access Validation." },
      { name: "Application Fee", amount: 7, frequency: "per_species", required: true, notes: "Non-refundable per species application." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit. Pure random lottery — no points, everyone has equal odds. Apply every year for a chance.",
    applicationTips: [
      "No points system — pure lottery. Apply every single year, it costs almost nothing.",
      "NM is the great equalizer. A first-time applicant has the same odds as a 10-year veteran.",
      "Some of the best elk hunting in the West. Quality units like 34 (Valles Caldera) are world-class.",
      "Just $13/species to apply. NR game-hunting license ($65) and HMAV ($4) required if drawn.",
    ],
    availableSpecies: ["elk", "mule_deer", "coues_deer", "black_bear", "pronghorn", "bighorn_sheep", "mountain_lion"],
    drawResultDates: { elk: "2026-06-15", mule_deer: "2026-06-15", black_bear: "2026-06-15", coues_deer: "2026-06-15", pronghorn: "2026-06-15", bighorn_sheep: "2026-06-15", mountain_lion: "2026-06-15" },
    pointCost: { elk: 0, mule_deer: 0, coues_deer: 0, black_bear: 0, pronghorn: 0, bighorn_sheep: 0, mountain_lion: 0 },
    tagCosts: { elk: 548, mule_deer: 283, coues_deer: 283, black_bear: 260, pronghorn: 283, bighorn_sheep: 3173, mountain_lion: 290 },
    residentTagCosts: { elk: 90, mule_deer: 41, coues_deer: 41, black_bear: 47, pronghorn: 60, bighorn_sheep: 160, mountain_lion: 43 },
    color: "#EA580C",
    lastScrapedAt: "2026-02-20",
    sourceUrl: "https://www.wildlife.state.nm.us/hunting",
    dataVersion: "2026.1",
    logistics: {
      primaryAirport: "ABQ (Albuquerque International Sunport)",
      secondaryAirports: ["SAF (Santa Fe)"],
      rentalCarNotes: "4WD helpful for mountain units but not always required. ABQ has full rental car selection. Roads in NM are generally better maintained than MT/WY backcountry. Carry water — it's desert country.",
      meatProcessing: "Santa Fe Custom Meats, Albuquerque processors, Raton Locker (northern NM). Ship from ABQ FedEx. Budget $150-200 for elk.",
      drivingNotes: "ABQ to northern NM elk country (Units 34, 6, 15): 2-3 hrs via I-25 N. ABQ to Gila area (southern): 3-4 hrs via I-25 S → Hwy 152. Central location makes most units accessible same day.",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 1-24", notes: "Bugling season in high country. Pine/aspen forests. Cool mornings.", bestFor: "backpack" },
      { tier: "Muzzleloader", dates: "Oct 1-9", notes: "Transition season. Elk less vocal but still patternable.", bestFor: "any" },
      { tier: "1st Rifle", dates: "Oct 15-19", notes: "5-day season. High success in quality units.", bestFor: "any" },
      { tier: "2nd Rifle", dates: "Nov 1-5", notes: "Elk moving to lower elevations. Good for truck-camp glassing.", bestFor: "truck_camp" },
      { tier: "3rd Rifle (Youth/Mobility)", dates: "Nov 22-26", notes: "Late season. Limited entry. Great for Thanksgiving trip hunts.", bestFor: "truck_camp" },
    ],
    statePersonality: "New Mexico is your wild card lottery ticket. No points, no waiting — just $13 and pure luck. Apply every single year because it costs almost nothing and the quality is world-class. Units like 34 (Valles Caldera) and 6 (Sangre de Cristos) produce bulls rivaling anywhere in the West. NM also has some of the earliest draw results, so if you draw here, you can adjust your other state plans accordingly. The terrain ranges from high desert to alpine meadows, and the Southwestern hunting culture is unique. NM is the ultimate bonus opportunity in any portfolio.",
  },
  {
    id: "OR",
    name: "Oregon",
    abbreviation: "OR",
    pointSystem: "hybrid",
    pointSystemDetails: {
      preferencePct: 75,
      randomPct: 25,
      description: "75% preference, 25% random draw for controlled hunts.",
    },
    fgUrl: "https://www.dfw.state.or.us",
    buyPointsUrl: "https://www.dfw.state.or.us/resources/hunting/",
    applicationDeadlines: {
      elk: { open: "2026-03-01", close: "2026-05-15" },
      mule_deer: { open: "2026-03-01", close: "2026-05-15" },
      blacktail: { open: "2026-03-01", close: "2026-05-15" },
      black_bear: { open: "2026-03-01", close: "2026-05-15" },
      pronghorn: { open: "2026-03-01", close: "2026-05-15" },
      bighorn_sheep: { open: "2026-03-01", close: "2026-05-15" },
      mountain_goat: { open: "2026-03-01", close: "2026-05-15" },
      mountain_lion: { open: "2026-03-01", close: "2026-05-15" },
    },
    deadlineTimezone: "America/Los_Angeles",
    onceInALifetime: ["bighorn_sheep", "mountain_goat"],
    licenseFees: { qualifyingLicense: 0, appFee: 8, pointFee: 0 },
    feeSchedule: [
      { name: "NR Application Fee", amount: 8, frequency: "per_species", required: true, notes: "Cheap application. No license required to apply." },
    ],
    residentLicenseFees: { qualifyingLicense: 39, appFee: 10, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Hunting License", amount: 39, frequency: "annual", required: true, notes: "Required to apply for controlled hunts. Effective 2026." },
      { name: "Controlled Hunt Application", amount: 10, frequency: "per_species", required: true, notes: "Per species controlled hunt application." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit for controlled hunts. 75/25 preference/random split. Some general season hunts are OTC.",
    applicationTips: [
      "One of the cheapest states to apply in — only $8/species. No excuse not to apply.",
      "General season Roosevelt elk hunts in western OR are often OTC (no draw needed).",
      "Eastern OR controlled hunts offer better trophy quality but require points.",
      "Late application deadline (May) gives you time to plan after other state results.",
    ],
    availableSpecies: ["elk", "mule_deer", "blacktail", "black_bear", "pronghorn", "bighorn_sheep", "mountain_goat", "mountain_lion"],
    drawResultDates: { elk: "2026-07-01", mule_deer: "2026-07-01", black_bear: "2026-07-01", blacktail: "2026-07-01", pronghorn: "2026-07-01", bighorn_sheep: "2026-07-01", mountain_goat: "2026-07-01", mountain_lion: "2026-07-01" },
    pointCost: { elk: 8, mule_deer: 8, blacktail: 8, black_bear: 8, pronghorn: 8, bighorn_sheep: 8, mountain_goat: 8, mountain_lion: 8 },
    tagCosts: { elk: 588, mule_deer: 443.50, blacktail: 443.50, black_bear: 16.50, pronghorn: 395.50, bighorn_sheep: 1513.50, mountain_goat: 1513.50, mountain_lion: 16.50 },
    residentTagCosts: { elk: 49.50, mule_deer: 28.50, blacktail: 28.50, black_bear: 16.50, pronghorn: 51.50, bighorn_sheep: 142, mountain_goat: 142, mountain_lion: 16.50 },
    color: "#16A34A",
    lastScrapedAt: "2026-02-20",
    sourceUrl: "https://myodfw.com/hunting",
    dataVersion: "2026.1",
    logistics: {
      primaryAirport: "PDX (Portland International)",
      secondaryAirports: ["RDM (Redmond/Bend)", "MFR (Medford)"],
      rentalCarNotes: "4WD recommended for eastern OR backcountry. PDX has full selection. RDM is closer to central OR hunting areas. Roads in western OR are generally good; eastern OR can be rough.",
      meatProcessing: "Bend Custom Meats, Prineville Locker, La Grande processors. Ship from RDM or PDX FedEx.",
      drivingNotes: "PDX to eastern OR (Starkey, Ochoco): 3-5 hrs via I-84 E or Hwy 26. RDM to central OR units: 1-2 hrs. Western OR Roosevelt elk areas: 1-2 hrs from PDX.",
    },
    pointOnlyApplication: {
      instructions: "Apply through ODFW portal. If you don't draw, you automatically receive a preference point for $8. No separate point-only purchase needed.",
      purchaseUrl: "https://www.dfw.state.or.us/resources/hunting/",
      deadline: "May 15, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Aug 27 - Sep 25", notes: "Early opener. Roosevelt elk in western OR, Rocky Mountain elk in eastern OR.", bestFor: "backpack" },
      { tier: "1st Rifle (Controlled)", dates: "Oct 1-7", notes: "Short controlled hunt. Premium experience in limited units.", bestFor: "any" },
      { tier: "2nd Rifle (General)", dates: "Oct 15-21", notes: "General season. Higher pressure but accessible. OTC in some areas.", bestFor: "any" },
      { tier: "Late Rifle", dates: "Nov 5-11", notes: "Late season. Deer rut. Migration patterns.", bestFor: "truck_camp" },
    ],
    statePersonality: "Oregon is the sleeper value play. At just $8/species, it's the cheapest state to apply in — there's no reason NOT to have OR in your portfolio. The 75/25 hybrid system builds points predictably for eastern OR controlled hunts, while western OR Roosevelt elk hunts are often OTC. The late application deadline (May) is strategically perfect — you'll know your draw results from CO, WY, and AZ before you even need to apply. Oregon rewards the patient hunter who builds points quietly while taking OTC opportunities in the meantime.",
  },
  {
    id: "ID",
    name: "Idaho",
    abbreviation: "ID",
    pointSystem: "random",
    pointSystemDetails: {
      description: "Pure random draw. No point system. Everyone has equal odds.",
    },
    fgUrl: "https://idfg.idaho.gov",
    buyPointsUrl: "https://idfg.idaho.gov/licenses",
    applicationDeadlines: {
      elk: { open: "2025-12-05", close: "2025-12-15" },
      mule_deer: { open: "2025-12-05", close: "2025-12-15" },
      black_bear: { open: "2026-04-01", close: "2026-04-30" },
      grizzly: { open: "2025-12-05", close: "2025-12-15" },
      moose: { open: "2025-12-05", close: "2025-12-15" },
      whitetail: { open: "2025-12-05", close: "2025-12-15" },
      pronghorn: { open: "2025-12-05", close: "2025-12-15" },
      bighorn_sheep: { open: "2025-12-05", close: "2025-12-15" },
      mountain_goat: { open: "2025-12-05", close: "2025-12-15" },
      mountain_lion: { open: "2025-12-05", close: "2025-12-15" },
      wolf: { open: "2025-12-05", close: "2025-12-15" },
    },
    deadlineTimezone: "America/Boise",
    onceInALifetime: ["moose", "bighorn_sheep", "mountain_goat"],
    licenseFees: { qualifyingLicense: 185, appFee: 18, pointFee: 0 },
    feeSchedule: [
      { name: "NR Hunting License", amount: 185, frequency: "annual", required: true, notes: "Required to hunt. Includes general deer/elk tags for general zones." },
      { name: "Controlled Hunt Application", amount: 18, frequency: "per_species", required: false, notes: "Per controlled hunt application (deer, elk, pronghorn, bear, turkey)." },
      { name: "Trophy Species Application", amount: 45.75, frequency: "per_species", required: false, notes: "For moose, bighorn sheep, mountain goat controlled hunts." },
      { name: "NR Elk Tag (if drawn)", amount: 651.75, frequency: "once", required: false, notes: "Additional tag required for controlled elk hunts, on top of license." },
      { name: "NR Deer Tag (if drawn)", amount: 351.75, frequency: "once", required: false, notes: "Additional tag required for controlled deer hunts, on top of license." },
      { name: "NR Bear Tag", amount: 231.75, frequency: "once", required: false, notes: "Required to hunt black bear." },
    ],
    residentLicenseFees: { qualifyingLicense: 15.75, appFee: 6.25, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Hunting License", amount: 15.75, frequency: "annual", required: true, notes: "Adult resident hunting license." },
      { name: "Controlled Hunt Application", amount: 6.25, frequency: "per_species", required: false, notes: "Per controlled hunt application." },
      { name: "Trophy Species Application", amount: 16.75, frequency: "per_species", required: false, notes: "For moose, bighorn sheep, mountain goat controlled hunts." },
    ],
    applicationApproach: "per_state",
    applicationApproachDescription: "Zone-based system. General tags come with your license. Controlled hunts are per-unit draw with no points — pure random.",
    applicationTips: [
      "Your NR hunting license IS your general elk/deer tag for most zones. You can hunt general without drawing.",
      "Controlled hunts are pure random — no points, just luck. Apply every year.",
      "Idaho has some of the most diverse opportunities: elk, deer, bear, moose, whitetail, wolf.",
      "Super early deadline (December) — easiest one to miss. Set a calendar reminder.",
      "Spring bear is a separate application window in April.",
    ],
    availableSpecies: ["elk", "mule_deer", "black_bear", "grizzly", "moose", "whitetail", "pronghorn", "bighorn_sheep", "mountain_goat", "mountain_lion", "wolf"],
    drawResultDates: { elk: "2026-02-15", mule_deer: "2026-02-15", black_bear: "2026-06-01", moose: "2026-02-15", whitetail: "2026-02-15", grizzly: "2026-02-15", pronghorn: "2026-02-15", bighorn_sheep: "2026-02-15", mountain_goat: "2026-02-15", mountain_lion: "2026-02-15", wolf: "2026-02-15" },
    pointCost: { elk: 0, mule_deer: 0, black_bear: 0, grizzly: 0, moose: 0, whitetail: 0, pronghorn: 0, bighorn_sheep: 0, mountain_goat: 0, mountain_lion: 0, wolf: 0 },
    tagCosts: { elk: 651.75, mule_deer: 351.75, black_bear: 231.75, grizzly: 1000, moose: 2626.75, whitetail: 351.75, pronghorn: 342.75, bighorn_sheep: 2626.75, mountain_goat: 2626.75, mountain_lion: 204.50, wolf: 31.75 },
    residentTagCosts: { elk: 30.75, mule_deer: 19.75, black_bear: 11.75, grizzly: 186, moose: 195.75, whitetail: 19.75, pronghorn: 19.75, bighorn_sheep: 195.75, mountain_goat: 195.75, mountain_lion: 11.75, wolf: 11.75 },
    color: "#0891B2",
    lastScrapedAt: "2026-02-20",
    sourceUrl: "https://idfg.idaho.gov/hunt",
    dataVersion: "2026.1",
    logistics: {
      primaryAirport: "BOI (Boise Airport)",
      secondaryAirports: ["IDA (Idaho Falls)", "SUN (Sun Valley)", "LWS (Lewiston)"],
      rentalCarNotes: "4WD essential for Idaho backcountry. BOI has good rental selection. IDA works for eastern ID units. Reserve early — fall hunting season depletes 4WD inventory. Many roads are unimproved forest service trails.",
      meatProcessing: "Idaho processors in Boise, McCall, Salmon, and Idaho Falls. D&B Custom Meats (Boise), Salmon Valley Meats. Ship from BOI FedEx. Budget $200-300 for elk.",
      drivingNotes: "BOI to central ID (Frank Church area): 3-4 hrs. BOI to Sawtooth Zone: 2.5 hrs via Hwy 21. IDA to eastern units: 1-2 hrs. Idaho is remote — plan extra drive time.",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Aug 30 - Sep 30", notes: "Bugling season. Backcountry wilderness areas. Remote and wild.", bestFor: "backpack" },
      { tier: "General Rifle", dates: "Oct 10 - Nov 18", notes: "Long general season. Your NR license IS your tag for general zones. No draw needed.", bestFor: "any" },
      { tier: "Controlled Hunt", dates: "Varies by unit", notes: "Draw-only hunts for premium units. Random draw, no points needed.", bestFor: "any" },
      { tier: "Spring Bear", dates: "Apr 15 - Jun 30", notes: "Excellent spring bear spot-and-stalk. Separate application. Green hillside glassing.", bestFor: "truck_camp" },
    ],
    statePersonality: "Idaho is the Swiss Army knife of western hunting states. Your NR hunting license ($185) IS your general elk and deer tag — no draw needed for general zones. That means you can hunt Idaho every single year, guaranteed. Controlled hunts for premium units are pure random draw with no points, so apply every year for a bonus shot. Idaho also has the earliest application deadline (December!) — set a calendar alarm or you'll miss it. The state offers elk, mule deer, whitetail, moose, bear, and wolf across terrain ranging from alpine wilderness to rolling prairie. Spring bear is an excellent add-on trip.",
  },
  {
    id: "KS",
    name: "Kansas",
    abbreviation: "KS",
    pointSystem: "preference_nr",
    pointSystemDetails: {
      description: "Preference points for nonresident deer only.",
    },
    fgUrl: "https://ksoutdoors.com",
    buyPointsUrl: "https://ksoutdoors.com/Hunting/Big-Game-Hunting",
    applicationDeadlines: {
      mule_deer: { open: "2026-04-01", close: "2026-04-28" },
      whitetail: { open: "2026-04-01", close: "2026-04-28" },
    },
    deadlineTimezone: "America/Chicago",
    licenseFees: { qualifyingLicense: 127.50, appFee: 27.50, pointFee: 0 },
    feeSchedule: [
      { name: "NR Hunting License", amount: 127.50, frequency: "annual", required: true, notes: "Required to hunt if drawn. Must have at time of application." },
      { name: "NR Deer Application", amount: 27.50, frequency: "per_species", required: true, notes: "Application fee per species. Doubles as preference point purchase." },
    ],
    residentLicenseFees: { qualifyingLicense: 0, appFee: 0, pointFee: 12.50 },
    residentFeeSchedule: [
      { name: "Preference Point", amount: 12.50, frequency: "per_species", required: false, notes: "Resident preference point for firearm deer permit." },
    ],
    residentPointCost: { mule_deer: 12.50, whitetail: 12.50, pronghorn: 12.50 },
    applicationApproach: "per_state",
    applicationApproachDescription: "Statewide NR deer draw with preference points. One of the best whitetail destinations in the country.",
    applicationTips: [
      "Kansas is the premier western whitetail destination for non-residents.",
      "Preference points mean patience pays — build points if you want a specific unit.",
      "Mule deer are available in western KS but limited. Whitetail is the main attraction.",
      "NR deer permit includes either-species in most units.",
    ],
    availableSpecies: ["mule_deer", "whitetail", "pronghorn"],
    drawResultDates: { mule_deer: "2026-06-01", whitetail: "2026-06-01", pronghorn: "2026-06-01" },
    pointCost: { mule_deer: 27.50, whitetail: 27.50, pronghorn: 27.50 },
    tagCosts: { mule_deer: 477.50, whitetail: 477.50, pronghorn: 302.50 },
    residentTagCosts: { mule_deer: 52.50, whitetail: 52.50, pronghorn: 52.50 },
    color: "#CA8A04",
    lastScrapedAt: "2026-02-20",
    sourceUrl: "https://ksoutdoors.com/Hunting",
    dataVersion: "2026.1",
    logistics: {
      primaryAirport: "MCI (Kansas City International)",
      secondaryAirports: ["ICT (Wichita)", "GCK (Garden City)"],
      rentalCarNotes: "2WD is fine for most KS hunting. MCI has full rental selection. Western KS mule deer areas accessible via GCK. Farm roads are well-maintained dirt.",
      meatProcessing: "Kansas processors are plentiful. Dodge City Custom Meats (western KS), multiple KC-area processors. Ship from MCI or GCK FedEx.",
      drivingNotes: "MCI to western KS mule deer: 5-6 hrs via I-70 W. MCI to central KS whitetail: 2-3 hrs. KS is flat — drives are easy and fast.",
    },
    pointOnlyApplication: {
      instructions: "Apply through KDWPT portal for NR deer permit. If not drawn, you automatically receive a preference point. $27.50 per species.",
      purchaseUrl: "https://ksoutdoors.com/Hunting/Big-Game-Hunting",
      deadline: "April 28, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 14 - Dec 31", notes: "Long archery season. Rut action mid-November. Best for whitetail.", bestFor: "any" },
      { tier: "Muzzleloader", dates: "Sep 14-28", notes: "Early season. Hot weather. Patterns from summer still hold.", bestFor: "any" },
      { tier: "Rifle (Regular)", dates: "Nov 29 - Dec 10", notes: "Short rifle season. Post-rut bucks still moving. Cold weather.", bestFor: "truck_camp" },
      { tier: "Pre-Rut Whitetail", dates: "Oct 15 - Nov 5", notes: "Bucks establishing scrapes and rub lines. Perfect time for stand hunting.", bestFor: "any" },
      { tier: "Peak Rut Whitetail", dates: "Nov 5-20", notes: "Peak rut. Bucks on their feet all day. Best chance at a giant.", bestFor: "any" },
    ],
    statePersonality: "Kansas is the whitetail wildcard in your western portfolio. While everyone else is chasing elk in the mountains, KS produces some of the biggest whitetail bucks in North America. The NR preference point system makes it predictable — build 1-2 points and you're drawing. November rut hunts in the eastern KS river bottoms are legendary. Western KS also offers mule deer on agricultural land. At $27.50/year, it's a cheap addition that diversifies your portfolio beyond mountain hunts. Perfect for a Thanksgiving-week hunt trip.",
  },
  {
    id: "WA",
    name: "Washington",
    abbreviation: "WA",
    pointSystem: "hybrid",
    pointSystemDetails: {
      preferencePct: 75,
      randomPct: 25,
      description: "75% preference, 25% random for special permit hunts.",
    },
    fgUrl: "https://wdfw.wa.gov",
    buyPointsUrl: "https://wdfw.wa.gov/hunting/requirements/special-hunts",
    applicationDeadlines: {
      elk: { open: "2026-04-01", close: "2026-05-22" },
      mule_deer: { open: "2026-04-01", close: "2026-05-22" },
      blacktail: { open: "2026-04-01", close: "2026-05-22" },
      black_bear: { open: "2026-04-01", close: "2026-05-22" },
      moose: { open: "2026-04-01", close: "2026-05-22" },
      mountain_goat: { open: "2026-04-01", close: "2026-05-22" },
      bighorn_sheep: { open: "2026-04-01", close: "2026-05-22" },
      mountain_lion: { open: "2026-04-01", close: "2026-05-22" },
    },
    deadlineTimezone: "America/Los_Angeles",
    licenseFees: { qualifyingLicense: 1188.04, appFee: 152.30, pointFee: 0 },
    feeSchedule: [
      { name: "NR Big Game Combo License (Deer+Elk+Bear+Cougar)", amount: 1188.04, frequency: "annual", required: true, notes: "Includes deer, elk, bear, and cougar tags. Required to hunt." },
      { name: "NR Special Permit Application", amount: 152.30, frequency: "per_species", required: true, notes: "Per species special permit application for draw hunts." },
    ],
    residentLicenseFees: { qualifyingLicense: 133.03, appFee: 9.61, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Big Game Combo License (Deer+Elk+Bear+Cougar)", amount: 133.03, frequency: "annual", required: true, notes: "Includes deer, elk, bear, cougar tags." },
      { name: "Special Permit Application", amount: 9.61, frequency: "per_species", required: true, notes: "Per species special permit draw application." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per hunt with up to 5 choices. 75/25 preference/random for special permit hunts. General season elk tags come with your big game license.",
    applicationTips: [
      "Your big game license IS your general elk/deer tag. Special permits are draw-only.",
      "General season elk is guaranteed with your license — no draw needed for many units.",
      "Washington has Roosevelt elk on the coast and Rocky Mountain elk in the east — completely different hunts.",
      "Late application deadline (May) gives you flexibility after other state results.",
    ],
    availableSpecies: ["elk", "mule_deer", "blacktail", "black_bear", "moose", "mountain_goat", "bighorn_sheep", "mountain_lion"],
    drawResultDates: { elk: "2026-06-15", mule_deer: "2026-06-15", moose: "2026-06-15", blacktail: "2026-06-15", black_bear: "2026-06-15", mountain_goat: "2026-06-15", bighorn_sheep: "2026-06-15", mountain_lion: "2026-06-15" },
    pointCost: { elk: 152.30, mule_deer: 152.30, blacktail: 152.30, black_bear: 152.30, moose: 152.30, mountain_goat: 152.30, bighorn_sheep: 152.30, mountain_lion: 152.30 },
    tagCosts: { elk: 685.60, mule_deer: 599.07, blacktail: 599.07, black_bear: 306.10, moose: 2279, mountain_goat: 2279, bighorn_sheep: 2279, mountain_lion: 306.10 },
    residentTagCosts: { elk: 69.29, mule_deer: 61.70, blacktail: 61.70, black_bear: 32.86, moose: 457.40, mountain_goat: 457.40, bighorn_sheep: 457.40, mountain_lion: 32.86 },
    color: "#0E7490",
    lastScrapedAt: "2026-02-20",
    logistics: {
      primaryAirport: "SEA (Seattle-Tacoma International)",
      secondaryAirports: ["GEG (Spokane)", "PSC (Tri-Cities)"],
      rentalCarNotes: "4WD recommended for eastern WA backcountry and mountain hunts. SEA has full rental selection. GEG is closer to eastern WA elk units. Chain requirements in mountain passes October-April.",
      meatProcessing: "Processors in Ellensburg, Yakima, Wenatchee, and Spokane. Ship from SEA or GEG FedEx.",
      drivingNotes: "SEA to eastern WA elk country: 2-3 hrs via I-90 E. GEG to NE WA moose units: 2-3 hrs. Mountain passes (Snoqualmie, Stevens) can close in winter.",
    },
    pointOnlyApplication: {
      instructions: "Apply through WDFW WILD system. If not drawn for your special permit, you automatically receive a preference point. Application fee ($7.10) is your point investment.",
      purchaseUrl: "https://wdfw.wa.gov/hunting/requirements/special-hunts",
      deadline: "May 22, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 1-30", notes: "Early archery for elk and deer. Roosevelt elk in western WA, Rocky Mountain elk in eastern WA.", bestFor: "any" },
      { tier: "Modern Firearm", dates: "Oct 15 - Nov 15", notes: "General season. Your license IS your tag for general units. Special permit units have higher quality.", bestFor: "any" },
      { tier: "Muzzleloader", dates: "Oct 1-14", notes: "Short muzzleloader season. Lower pressure between archery and rifle.", bestFor: "any" },
      { tier: "Late Season", dates: "Nov 15 - Dec 15", notes: "Late season in select units. Cold weather moves animals. Good for mule deer.", bestFor: "truck_camp" },
    ],
    statePersonality: "Washington is the Pacific Northwest sleeper. Your big game license gives you a general elk and deer tag — no draw needed, hunt every year. Special permits for premium units use a 75/25 preference system to reward patience. Western WA offers Roosevelt elk in old-growth rainforest, while eastern WA has classic Rocky Mountain elk in sage and timber. At just $7.10 to apply, WA is one of the cheapest states to add to your portfolio. The late deadline (May) means you'll know your other state results before committing.",
  },
  {
    id: "NE",
    name: "Nebraska",
    abbreviation: "NE",
    pointSystem: "preference",
    pointSystemDetails: {
      preferencePct: 100,
      description: "True preference point system. Tags go to highest point holders first.",
    },
    fgUrl: "https://outdoornebraska.gov",
    buyPointsUrl: "https://outdoornebraska.gov/bigdeerseasonapplication/",
    applicationDeadlines: {
      elk: { open: "2026-01-01", close: "2026-03-15" },
      mule_deer: { open: "2026-01-01", close: "2026-03-15" },
      whitetail: { open: "2026-01-01", close: "2026-03-15" },
      pronghorn: { open: "2026-01-01", close: "2026-05-01" },
      bighorn_sheep: { open: "2026-01-01", close: "2026-03-15" },
    },
    deadlineTimezone: "America/Chicago",
    licenseFees: { qualifyingLicense: 0, appFee: 10, pointFee: 26 },
    feeSchedule: [
      { name: "NR Application Fee", amount: 10, frequency: "per_species", required: true, notes: "Non-refundable application fee per species." },
      { name: "NR Preference Point", amount: 26, frequency: "per_species", required: false, notes: "Purchase separately if not applying for a tag." },
    ],
    residentLicenseFees: { qualifyingLicense: 0, appFee: 11, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Application Fee", amount: 11, frequency: "per_species", required: true, notes: "Non-refundable per species." },
    ],
    residentPointCost: { elk: 0, mule_deer: 0, whitetail: 0, pronghorn: 0, bighorn_sheep: 0 },
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit. True preference system — highest point holders draw first. Limited NR elk tags make this a long-term play.",
    applicationTips: [
      "Nebraska elk tags are extremely limited for NR — often single-digit quotas. It's a long-term point build.",
      "Mule deer in the Pine Ridge and Wildcat Hills are excellent. Draws with 1-3 preference points.",
      "Pronghorn is relatively easy to draw and offers great hunting in the Sandhills.",
      "No qualifying license needed to buy preference points.",
    ],
    availableSpecies: ["elk", "mule_deer", "whitetail", "pronghorn", "bighorn_sheep"],
    drawResultDates: { elk: "2026-05-01", mule_deer: "2026-05-01", pronghorn: "2026-06-15", whitetail: "2026-05-01", bighorn_sheep: "2026-05-01" },
    pointCost: { elk: 26, mule_deer: 26, whitetail: 26, pronghorn: 26, bighorn_sheep: 26 },
    tagCosts: { elk: 542, mule_deer: 335, whitetail: 335, pronghorn: 241, bighorn_sheep: 1500 },
    residentTagCosts: { elk: 189, mule_deer: 37, whitetail: 37, pronghorn: 43, bighorn_sheep: 175 },
    color: "#9333EA",
    lastScrapedAt: "2026-02-20",
    logistics: {
      primaryAirport: "OMA (Eppley Airfield, Omaha)",
      secondaryAirports: ["LNK (Lincoln)", "RAP (Rapid City, SD — for Pine Ridge)"],
      rentalCarNotes: "2WD is fine for most NE hunting. 4WD helpful in Pine Ridge area after rain. OMA has good rental selection. RAP (Rapid City SD) is closer to Pine Ridge elk/deer units.",
      meatProcessing: "Chadron Custom Meats, Alliance processors for western NE. Omaha processors for eastern hunts. Budget $100-200 for processing.",
      drivingNotes: "OMA to Pine Ridge (NW NE): 5-6 hrs via I-80 W → Hwy 71 N. RAP to Pine Ridge: 1.5 hrs. Sandhills pronghorn: 3-4 hrs from OMA.",
    },
    pointOnlyApplication: {
      instructions: "Apply through Nebraska Game & Parks portal. Select 'preference point only' option. $26 point + $10 app fee = $36/species/year.",
      purchaseUrl: "https://outdoornebraska.gov/bigdeerseasonapplication/",
      deadline: "March 15, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 15 - Dec 31", notes: "Long archery season. Whitetail rut in November is prime. Mule deer in Pine Ridge.", bestFor: "any" },
      { tier: "Rifle (Mule Deer)", dates: "Nov 14-22", notes: "Pine Ridge and Wildcat Hills. Short but productive rifle season.", bestFor: "truck_camp" },
      { tier: "Rifle (Elk)", dates: "Oct 1-31", notes: "Limited NR elk season. Pine Ridge and Sandhills. Premium draw.", bestFor: "any" },
      { tier: "Pronghorn", dates: "Sep 20 - Oct 31", notes: "Sandhills and western NE. Good draw odds. Spot-and-stalk in open terrain.", bestFor: "truck_camp" },
    ],
    statePersonality: "Nebraska is the hidden gem of the plains. The Pine Ridge in NW Nebraska holds genuine trophy mule deer and a small but growing elk herd — most hunters don't even know NE has elk. Pronghorn in the Sandhills is easy to draw and offers classic spot-and-stalk hunting in vast open country. The true preference system means your draw is predictable — you know exactly when you'll get your tag. At $36/year for points, it's an affordable long-term play that most NR hunters overlook.",
  },
  {
    id: "SD",
    name: "South Dakota",
    abbreviation: "SD",
    pointSystem: "preference",
    pointSystemDetails: {
      preferencePct: 100,
      description: "True preference point system. Highest point holders draw first. Second draw is random.",
    },
    fgUrl: "https://gfp.sd.gov",
    buyPointsUrl: "https://gfp.sd.gov/hunting/",
    applicationDeadlines: {
      elk: { open: "2026-01-01", close: "2026-03-31" },
      mule_deer: { open: "2026-01-01", close: "2026-03-31" },
      whitetail: { open: "2026-01-01", close: "2026-03-31" },
      pronghorn: { open: "2026-01-01", close: "2026-03-31" },
      bighorn_sheep: { open: "2026-01-01", close: "2026-03-31" },
      mountain_goat: { open: "2026-01-01", close: "2026-03-31" },
      mountain_lion: { open: "2026-01-01", close: "2026-03-31" },
    },
    deadlineTimezone: "America/Chicago",
    licenseFees: { qualifyingLicense: 0, appFee: 10, pointFee: 30 },
    feeSchedule: [
      { name: "NR Application Fee", amount: 10, frequency: "per_species", required: true, notes: "Non-refundable application fee." },
      { name: "NR Preference Point", amount: 30, frequency: "per_species", required: false, notes: "Buy separately if not applying for a tag." },
    ],
    residentLicenseFees: { qualifyingLicense: 0, appFee: 10, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Habitat Stamp", amount: 10, frequency: "annual", required: true, notes: "Required for all hunting licenses." },
      { name: "Application Fee", amount: 10, frequency: "per_species", required: true, notes: "For elk, sheep, goat. No fee for deer/antelope." },
    ],
    residentPointCost: { elk: 0, mule_deer: 0, whitetail: 0, pronghorn: 0, bighorn_sheep: 0, mountain_goat: 0, mountain_lion: 0 },
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit. True preference point system with second draw random. Build points for premium Black Hills units.",
    applicationTips: [
      "Black Hills elk is the crown jewel — extremely limited NR tags but world-class quality.",
      "Prairie pronghorn is easy to draw and offers great DIY spot-and-stalk hunting.",
      "Mule deer in the badlands are an underrated trophy opportunity.",
      "SD also offers mountain goat and bighorn sheep permits — rare but attainable with patience.",
    ],
    availableSpecies: ["elk", "mule_deer", "whitetail", "pronghorn", "bighorn_sheep", "mountain_goat", "mountain_lion"],
    drawResultDates: { elk: "2026-05-15", mule_deer: "2026-05-15", pronghorn: "2026-05-15", whitetail: "2026-05-15", bighorn_sheep: "2026-05-15", mountain_goat: "2026-05-15", mountain_lion: "2026-05-15" },
    pointCost: { elk: 30, mule_deer: 30, whitetail: 30, pronghorn: 30, bighorn_sheep: 30, mountain_goat: 30, mountain_lion: 30 },
    tagCosts: { elk: 0, mule_deer: 375, whitetail: 375, pronghorn: 375, bighorn_sheep: 0, mountain_goat: 0, mountain_lion: 0 },
    residentTagCosts: { elk: 195, mule_deer: 40, whitetail: 40, pronghorn: 36, bighorn_sheep: 294, mountain_goat: 275, mountain_lion: 24 },
    color: "#2563EB",
    lastScrapedAt: "2026-02-20",
    logistics: {
      primaryAirport: "RAP (Rapid City Regional)",
      secondaryAirports: ["FSD (Sioux Falls)", "PIR (Pierre)"],
      rentalCarNotes: "2WD fine for most SD hunting. 4WD helpful in Black Hills after weather. RAP is the gateway to Black Hills and badlands hunting. Small airport — book early during hunting season.",
      meatProcessing: "Rapid City has several processors. Wall Drug Country processors for badlands hunts. Budget $100-200 for deer/pronghorn processing.",
      drivingNotes: "RAP to Black Hills elk units: 30 min - 1.5 hrs. RAP to badlands mule deer: 1-2 hrs via I-90 E. FSD to eastern SD whitetail: 1-2 hrs.",
    },
    pointOnlyApplication: {
      instructions: "Apply through SD GFP portal. Select 'preference point only' to build points without entering the draw. $30 point + $10 app = $40/species/year.",
      purchaseUrl: "https://gfp.sd.gov/hunting/",
      deadline: "March 31, 2026",
    },
    seasonTiers: [
      { tier: "Archery (Elk/Deer)", dates: "Sep 1 - Jan 1", notes: "Long archery season. Black Hills archery elk is special. Whitetail rut in November.", bestFor: "any" },
      { tier: "Black Hills Rifle (Elk)", dates: "Nov 1-30", notes: "Limited tags. Late-season Black Hills elk is a trophy experience. Cold weather.", bestFor: "any" },
      { tier: "West River Rifle (Deer)", dates: "Nov 14-30", notes: "Badlands and west river mule deer. Rut timing. Open terrain glassing.", bestFor: "truck_camp" },
      { tier: "Pronghorn", dates: "Oct 1-31", notes: "Prairie pronghorn. Good draw odds. Spot-and-stalk in vast grasslands.", bestFor: "truck_camp" },
    ],
    statePersonality: "South Dakota punches above its weight. Black Hills elk is among the highest quality in the country — limited tags, unhunted animals, and ponderosa pine terrain that's gorgeous to hunt. The true preference system means you know exactly when you'll draw. Prairie pronghorn is easy to draw and a blast to hunt DIY. Badlands mule deer during the November rut produce big-bodied, heavy-antlered bucks. SD also has mountain goat and bighorn sheep permits for the ultra-patient. At $40/year for elk points, it's a worthwhile long-term investment in a state most hunters overlook.",
  },
  {
    id: "ND",
    name: "North Dakota",
    abbreviation: "ND",
    pointSystem: "bonus",
    pointSystemDetails: {
      description: "Bonus point system for limited-entry species (elk, moose, bighorn sheep). Each bonus point adds one chance in the lottery draw.",
    },
    fgUrl: "https://gf.nd.gov",
    buyPointsUrl: "https://gf.nd.gov/hunting/",
    applicationDeadlines: {
      elk: { open: "2026-03-01", close: "2026-04-08" },
      mule_deer: { open: "2026-03-01", close: "2026-04-08" },
      whitetail: { open: "2026-03-01", close: "2026-04-08" },
      pronghorn: { open: "2026-03-01", close: "2026-06-03" },
      moose: { open: "2026-03-01", close: "2026-04-08" },
      bighorn_sheep: { open: "2026-03-01", close: "2026-04-08" },
    },
    deadlineTimezone: "America/Chicago",
    licenseFees: { qualifyingLicense: 0, appFee: 10, pointFee: 30 },
    feeSchedule: [
      { name: "NR Application Fee", amount: 10, frequency: "per_species", required: true, notes: "Per species application fee." },
      { name: "NR Bonus Point", amount: 30, frequency: "per_species", required: false, notes: "Purchase separately. Adds one chance in the lottery per point." },
    ],
    residentLicenseFees: { qualifyingLicense: 20, appFee: 5, pointFee: 0 },
    residentFeeSchedule: [
      { name: "General Game & Habitat License", amount: 20, frequency: "annual", required: true, notes: "Required for all hunting applications." },
      { name: "Certificate", amount: 2, frequency: "annual", required: true, notes: "Fishing/Hunting/Furbearer Certificate." },
      { name: "Application Fee", amount: 5, frequency: "per_species", required: true, notes: "Non-refundable per species." },
    ],
    residentPointCost: { elk: 0, mule_deer: 0, whitetail: 0, pronghorn: 0, moose: 0, bighorn_sheep: 0 },
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit. Bonus point system for elk, moose, and bighorn — each point adds one chance in the lottery. Deer licenses available through separate lottery.",
    applicationTips: [
      "NR elk tags are VERY limited — often under 100 for the whole state. Long-term point commitment.",
      "Moose permits are rare gems — limited to a handful of NR tags per year.",
      "Mule deer in the badlands are trophy-caliber with the right unit choice.",
      "Pronghorn in western ND is easy to draw and excellent quality.",
    ],
    availableSpecies: ["elk", "mule_deer", "whitetail", "pronghorn", "moose", "bighorn_sheep"],
    drawResultDates: { elk: "2026-05-15", mule_deer: "2026-05-15", pronghorn: "2026-07-01", moose: "2026-05-15", whitetail: "2026-05-15", bighorn_sheep: "2026-05-15" },
    pointCost: { elk: 30, mule_deer: 30, whitetail: 30, pronghorn: 30, moose: 30, bighorn_sheep: 30 },
    tagCosts: { elk: 0, mule_deer: 355, whitetail: 355, pronghorn: 0, moose: 0, bighorn_sheep: 600 },
    residentTagCosts: { elk: 35, mule_deer: 35, whitetail: 35, pronghorn: 35, moose: 35, bighorn_sheep: 35 },
    color: "#B45309",
    lastScrapedAt: "2026-02-20",
    logistics: {
      primaryAirport: "BIS (Bismarck Municipal)",
      secondaryAirports: ["FAR (Fargo)", "MOT (Minot)"],
      rentalCarNotes: "2WD fine for most ND hunting. 4WD helpful for badlands roads after rain. BIS is central to hunting areas. Small airports — limited but adequate rental options.",
      meatProcessing: "Bismarck, Dickinson, and Williston processors. Budget $100-200 for processing. Some will ship.",
      drivingNotes: "BIS to badlands elk/mule deer: 1-2 hrs via I-94 W. BIS to northern moose units: 2-3 hrs north. BIS to pronghorn in SW ND: 2 hrs.",
    },
    pointOnlyApplication: {
      instructions: "Apply through ND Game & Fish portal. Bonus point purchase available for elk, moose, and bighorn sheep. $30 point + $10 app = $40/species/year.",
      purchaseUrl: "https://gf.nd.gov/hunting/",
      deadline: "April 8, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 1 - Jan 3", notes: "Long archery season. Excellent badlands mule deer during November rut.", bestFor: "any" },
      { tier: "Rifle (Deer)", dates: "Nov 6-22", notes: "Short rifle season. Badlands mule deer rut. Cold weather concentrates animals.", bestFor: "truck_camp" },
      { tier: "Rifle (Elk)", dates: "Oct 1-30", notes: "Limited NR elk. Badlands habitat. Small herds but high-quality animals.", bestFor: "any" },
      { tier: "Pronghorn", dates: "Oct 1-31", notes: "Western ND grasslands. Good draw odds for NR. Classic spot-and-stalk.", bestFor: "truck_camp" },
    ],
    statePersonality: "North Dakota is the northern plains dark horse. Theodore Roosevelt's hunting grounds in the badlands still hold elk, mule deer, and moose — species most people don't associate with ND. NR elk tags are extremely limited, making this a serious long-term commitment, but the quality is exceptional. Badlands mule deer during the November rut are a trophy opportunity. Pronghorn draws easily and provides great DIY hunting. If you're willing to hunt in cold weather and open terrain, ND rewards you with uncrowded public land and quality animals at $40/year in point costs.",
  },
  {
    id: "AK",
    name: "Alaska",
    abbreviation: "AK",
    pointSystem: "random",
    pointSystemDetails: {
      description: "Draw permits are pure lottery. Most hunts are registration or general season — no draw needed.",
    },
    fgUrl: "https://www.adfg.alaska.gov",
    buyPointsUrl: "https://www.adfg.alaska.gov/index.cfm?adfg=huntlicense.main",
    applicationDeadlines: {
      moose: { open: "2025-11-01", close: "2025-12-15" },
      black_bear: { open: "2025-11-01", close: "2025-12-15" },
      grizzly: { open: "2025-11-01", close: "2025-12-15" },
      elk: { open: "2025-11-01", close: "2025-12-15" },
      bison: { open: "2025-11-01", close: "2025-12-15" },
      mountain_goat: { open: "2025-11-01", close: "2025-12-15" },
      dall_sheep: { open: "2025-11-01", close: "2025-12-15" },
      caribou: { open: "2025-11-01", close: "2025-12-15" },
    },
    deadlineTimezone: "America/Anchorage",
    licenseFees: { qualifyingLicense: 265, appFee: 10, pointFee: 0 },
    feeSchedule: [
      { name: "NR Hunting & Sport Fishing License", amount: 265, frequency: "annual", required: true, notes: "Required before hunting. Good for calendar year. Includes 14-day sport fishing." },
      { name: "NR Locking Tag (Moose)", amount: 800, frequency: "once", required: false, notes: "Metal locking tag. Required per animal harvested." },
      { name: "NR Locking Tag (Brown/Grizzly Bear)", amount: 1000, frequency: "once", required: false, notes: "Tag for brown/grizzly bear." },
      { name: "NR Locking Tag (Dall Sheep)", amount: 850, frequency: "once", required: false, notes: "NR guide required for sheep." },
      { name: "Draw Permit Application", amount: 10, frequency: "per_species", required: false, notes: "For draw-only hunts. Most hunts are registration or general." },
    ],
    residentLicenseFees: { qualifyingLicense: 25, appFee: 5, pointFee: 0 },
    residentFeeSchedule: [
      { name: "Hunting License", amount: 25, frequency: "annual", required: true, notes: "Resident annual hunting license." },
      { name: "Locking Tag (Moose)", amount: 0, frequency: "once", required: false, notes: "Free for residents. Required per animal harvested." },
      { name: "Locking Tag (Brown Bear)", amount: 25, frequency: "once", required: false, notes: "Resident brown/grizzly bear tag." },
      { name: "Draw Permit Application", amount: 5, frequency: "per_species", required: false, notes: "For draw-only hunts." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Most AK hunts are registration or general season — no draw needed, just buy license and tag. Draw permits for limited-entry areas are pure lottery.",
    applicationTips: [
      "Alaska is unique: most hunts are registration or general season. No draw required — just buy your license and locking tags.",
      "Draw permits for specific GMUs are pure random. Apply for premium areas while hunting general season as backup.",
      "NR locking tags are expensive ($800 moose, $650 brown bear) but give you access to incredible hunting.",
      "Very early application deadline (December!) — the earliest in the West. Don't miss it.",
      "Guide required for NR sheep, goat, and brown/grizzly bear hunts.",
    ],
    availableSpecies: ["elk", "moose", "black_bear", "grizzly", "sitka_blacktail", "mountain_goat", "dall_sheep", "bison", "caribou", "muskox", "wolf"],
    drawResultDates: { moose: "2026-02-15", black_bear: "2026-02-15", grizzly: "2026-02-15", elk: "2026-02-15", bison: "2026-02-15", dall_sheep: "2026-02-15", caribou: "2026-02-15", sitka_blacktail: "2026-02-15", mountain_goat: "2026-02-15", muskox: "2026-02-15", wolf: "2026-02-15" },
    pointCost: { elk: 0, moose: 0, black_bear: 0, grizzly: 0, sitka_blacktail: 0, mountain_goat: 0, dall_sheep: 0, bison: 0, caribou: 0, muskox: 0, wolf: 0 },
    tagCosts: { elk: 600, moose: 800, black_bear: 450, grizzly: 1000, sitka_blacktail: 300, mountain_goat: 600, dall_sheep: 850, bison: 900, caribou: 650, muskox: 2200, wolf: 60 },
    residentTagCosts: { elk: 30, moose: 0, black_bear: 25, grizzly: 25, sitka_blacktail: 0, mountain_goat: 40, dall_sheep: 40, bison: 100, caribou: 0, muskox: 100, wolf: 15 },
    color: "#14532D",
    lastScrapedAt: "2026-02-20",
    sourceUrl: "https://www.adfg.alaska.gov/index.cfm?adfg=hunting.main",
    dataVersion: "2026.1",
    logistics: {
      primaryAirport: "ANC (Ted Stevens Anchorage International)",
      secondaryAirports: ["FAI (Fairbanks)", "JNU (Juneau)"],
      rentalCarNotes: "Limited road system. Many hunts require bush planes, boats, or ATVs. Road-accessible hunts: Kenai Peninsula, Matanuska Valley, Denali corridor. 4WD essential where there are roads.",
      meatProcessing: "Indian Valley Meats (ANC), Fairbanks processors. Ship via Alaska Airlines cargo ($200-400). Remote hunts: quarter and fly out via bush plane.",
      drivingNotes: "ANC to Kenai Peninsula: 2.5 hrs via Seward Hwy. ANC to Matanuska Valley: 1.5 hrs via Glenn Hwy. Most premium hunts require bush plane access from ANC or FAI.",
    },
    seasonTiers: [
      { tier: "General Moose", dates: "Sep 1-20", notes: "Registration hunts for moose. Peak rut. Classic Alaska experience.", bestFor: "any" },
      { tier: "Brown Bear (Spring)", dates: "Apr 15 - May 31", notes: "Coastal brown bear. NR guide required. Big bears on beaches.", bestFor: "guided" },
      { tier: "Brown Bear (Fall)", dates: "Sep 1 - Oct 15", notes: "Interior grizzly and coastal brown bear. Salmon streams.", bestFor: "guided" },
      { tier: "Dall Sheep", dates: "Aug 10 - Sep 20", notes: "High alpine. NR guide required. Classic mountain hunt.", bestFor: "backpack" },
      { tier: "Caribou", dates: "Aug 1 - Sep 30", notes: "Tundra caribou. DIY possible via bush plane drop. Migration herds.", bestFor: "backpack" },
    ],
    statePersonality: "Alaska is the ultimate hunting frontier. Most hunts require no draw — buy your license and locking tags, then go. Registration moose hunts during the September rut are a genuine bucket-list experience. Brown bear on the coast, Dall sheep in the Alaska Range, and caribou on the North Slope are all accessible to NR hunters (guide required for sheep, goat, and brown bear). AK is more expensive per trip ($3,000-15,000 including bush planes and guides) but offers experiences found nowhere else. The December draw deadline is the earliest in the West — set a reminder. Add AK as your ultimate adventure play.",
  },
];

export const STATES_MAP = Object.fromEntries(STATES.map((s) => [s.id, s]));

export function getStateById(id: string): State | undefined {
  return STATES_MAP[id];
}
