import { State } from "@/lib/types";

export const STATES: State[] = [
  {
    id: "CO",
    name: "Colorado",
    abbreviation: "CO",
    pointSystem: "preference",
    pointSystemDetails: {
      preferencePct: 80,
      randomPct: 20,
      description: "True Preference with 80/20 hybrid. Tags go to highest point holders first.",
    },
    fgUrl: "https://cpw.state.co.us",
    buyPointsUrl: "https://cpw.state.co.us/activities/hunting/big-game/primary-draw",
    applicationDeadlines: {
      elk: { open: "2026-03-01", close: "2026-04-07" },
      mule_deer: { open: "2026-03-01", close: "2026-04-07" },
      bear: { open: "2026-03-01", close: "2026-04-07" },
      moose: { open: "2026-03-01", close: "2026-04-07" },
    },
    licenseFees: { qualifyingLicense: 101.54, appFee: 10, pointFee: 40 },
    feeSchedule: [
      { name: "Qualifying License", amount: 101.54, frequency: "annual", required: true, notes: "Required before applying. One-time annual purchase covers all species." },
      { name: "Application Fee", amount: 10, frequency: "per_species", required: true, notes: "Per application per species." },
      { name: "Preference Point", amount: 40, frequency: "per_species", required: false, notes: "Buy via point-only application if not drawing." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit. You list a first choice and second choice hunt code. Point-only strategy: pick point-only as first choice, actual hunt code as second.",
    applicationTips: [
      "Use the 2nd-choice tactic: list point-only as 1st choice, real unit as 2nd choice. You build a point AND get a shot at drawing.",
      "Qualifying license must be purchased before the draw — even if you're only buying points.",
      "OTC elk tags are available if you strike out in the draw. Over-the-counter 2nd/3rd rifle is always a backup.",
      "Moose, goat, and sheep are once-in-a-lifetime species in CO.",
    ],
    availableSpecies: ["elk", "mule_deer", "bear", "moose"],
    drawResultDates: { elk: "2026-06-01", mule_deer: "2026-06-01", bear: "2026-06-01", moose: "2026-06-01" },
    pointCost: { elk: 40, mule_deer: 40, bear: 40, moose: 40 },
    color: "#1E40AF",
    logistics: {
      primaryAirport: "DEN (Denver International)",
      secondaryAirports: ["GJT (Grand Junction)", "EGE (Eagle/Vail)", "HDN (Hayden/Steamboat)"],
      rentalCarNotes: "4WD SUV mandatory for NW Colorado forest roads — reserve early for September-November. Enterprise and National at DEN have best selection. Turo is a backup option for lifted trucks.",
      meatProcessing: "Ship quartered elk via FedEx cold pack from Craig or Meeker — $150-250 per animal. Local processors: Craig Custom Meats, Meeker Locker, Valley Meat Co (Rifle). Call ahead to schedule during rifle seasons.",
      drivingNotes: "DEN to NW CO units (3, 4, 11, 211): 3-4 hrs via I-70 W → Hwy 13 N. GJT to Unit 4/11 is ~2 hrs. HDN (Steamboat) is closest to Units 4/14 area.",
    },
    pointOnlyApplication: {
      instructions: "On the CPW online portal, select 'Preference Point Only' (code PP001) as your 1st choice hunt code. This builds a preference point with zero risk of drawing a tag.",
      huntCode: "PP001",
      secondChoiceTactic: "List PP001 as 1st choice, then your actual unit hunt code as 2nd choice. You earn a preference point AND enter the random pool for your 2nd-choice unit. Best of both worlds.",
      purchaseUrl: "https://cpw.state.co.us/activities/hunting/big-game/primary-draw",
      deadline: "April 7, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 2-30", notes: "Elk bugling season. Backcountry hunters thrive. Warm days, cold nights at 8,000+ ft.", bestFor: "backpack" },
      { tier: "Muzzleloader", dates: "Sep 12-22", notes: "Transition period. Elk still vocal but harder to pattern. Lower pressure than archery.", bestFor: "any" },
      { tier: "1st Rifle", dates: "Oct 14-18", notes: "5-day season. Heavy opening-morning pressure. Best for well-scouted locals and dedicated NR hunters.", bestFor: "any" },
      { tier: "2nd Rifle", dates: "Oct 22-30", notes: "Sweet spot for truck-camp hunters. Less pressure, elk transitioning to lower elevations. 9 days to hunt.", bestFor: "truck_camp" },
      { tier: "3rd Rifle", dates: "Nov 5-13", notes: "Mule deer rut begins. Cold weather pushes elk to winter range. Prime for glassing sage-to-timber transitions.", bestFor: "truck_camp" },
      { tier: "4th Rifle", dates: "Nov 17-21", notes: "Late season. Deep snow possible. Migration corridors are key. Dress warm, glass far.", bestFor: "truck_camp" },
    ],
    statePersonality: "Colorado is the workhorse of your portfolio. The preference point system is the most predictable in the West — you know exactly when you'll draw. The second-choice tactic is your secret weapon: build a point AND hunt every year. NW Colorado units (3, 4, 11, 211) are truck-friendly with high road density and strong public land access. OTC backup tags mean you can always go hunting even if you don't draw. At ~$151/year for elk points, it's one of the most capital-efficient investments in western hunting.",
  },
  {
    id: "WY",
    name: "Wyoming",
    abbreviation: "WY",
    pointSystem: "hybrid",
    pointSystemDetails: {
      preferencePct: 75,
      randomPct: 25,
      description: "75% of tags to highest points, 25% random draw.",
    },
    fgUrl: "https://wgfd.wyo.gov",
    buyPointsUrl: "https://wgfd.wyo.gov/hunting-trapping/preference-points",
    applicationDeadlines: {
      elk: { open: "2026-01-02", close: "2026-03-15" },
      mule_deer: { open: "2026-01-02", close: "2026-03-15" },
      moose: { open: "2026-01-02", close: "2026-03-15" },
    },
    licenseFees: { qualifyingLicense: 0, appFee: 15, pointFee: 55 },
    feeSchedule: [
      { name: "Application Fee", amount: 15, frequency: "per_species", required: true, notes: "Non-refundable application fee per species." },
      { name: "Preference Point", amount: 55, frequency: "per_species", required: false, notes: "Purchase separately if not applying for a tag." },
    ],
    applicationApproach: "per_region",
    applicationApproachDescription: "Apply by hunt area (region-based). Elk areas are grouped: Western, Southern, Eastern. Each area has different point creep.",
    applicationTips: [
      "WY is region-based for elk. Research which hunt areas fall in your target region before applying.",
      "Special tags (moose, sheep, goat) are separate draws with their own preference points.",
      "No qualifying license required to buy points — just the point fee.",
      "Point creep is real: popular areas like 100 (desert elk) are 5+ year investments.",
    ],
    availableSpecies: ["elk", "mule_deer", "moose"],
    drawResultDates: { elk: "2026-05-15", mule_deer: "2026-05-15", moose: "2026-05-15" },
    pointCost: { elk: 55, mule_deer: 55, moose: 55 },
    color: "#92400E",
    logistics: {
      primaryAirport: "JAC (Jackson Hole) or SLC (Salt Lake City)",
      secondaryAirports: ["CPR (Casper)", "SHR (Sheridan)", "BIL (Billings, MT — drive south)"],
      rentalCarNotes: "4WD is essential everywhere in WY. Rent at SLC or JAC — SLC has better prices and availability. Expect 3-5 hour drives from airport to most hunt areas. Gas stations are sparse; fill up at every opportunity.",
      meatProcessing: "Processors in Cody, Sheridan, and Lander. Ship FedEx cold pack from closest town — $200-300 for elk. Wyoming Meat Co (Cody) does full processing + shipping.",
      drivingNotes: "JAC to western elk areas: 1-3 hrs. SLC to western WY: 4-5 hrs via I-80 or US-89. Casper is central to many hunt areas. Long drives are part of WY hunting.",
    },
    pointOnlyApplication: {
      instructions: "On the WY Game & Fish portal, purchase a 'Preference Point Only' for your species. No qualifying license required. Just the point fee ($55) + app fee ($15) = $70/species.",
      huntCode: "Preference Point Only",
      purchaseUrl: "https://wgfd.wyo.gov/hunting-trapping/preference-points",
      deadline: "March 15, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 1-30", notes: "Bugling season. Backcountry access to wilderness areas. Best trophy potential.", bestFor: "backpack" },
      { tier: "General Rifle", dates: "Oct 1-31", notes: "Month-long season in most areas. Mix of pressure levels depending on area access.", bestFor: "any" },
      { tier: "Late Season", dates: "Nov 1-15", notes: "Cold weather hunts. Migration corridors key. Desert elk units peak in November.", bestFor: "truck_camp" },
    ],
    statePersonality: "Wyoming is your quality play. The 75/25 hybrid system rewards patience with a clear preference path, but still gives you a random-pool shot every year. Desert elk hunts (Area 100) are legendary — 80-90% success on mature bulls in sagebrush country, perfect for truck-camp glassers. The Bighorns offer classic timber elk with no grizzly pressure. Mule deer in the Wyoming Range are world-class during the late rut. WY requires longer drives and more logistical planning, but the payoff in animal quality per dollar is hard to beat.",
  },
  {
    id: "MT",
    name: "Montana",
    abbreviation: "MT",
    pointSystem: "dual",
    pointSystemDetails: {
      preferencePct: 75,
      randomPct: 25,
      squared: true,
      description: "Preference points for combo license (75/25). Bonus points (squared) for special permits.",
    },
    fgUrl: "https://fwp.mt.gov",
    buyPointsUrl: "https://fwp.mt.gov/buyandapply",
    applicationDeadlines: {
      elk: { open: "2026-03-01", close: "2026-04-01" },
      mule_deer: { open: "2026-03-01", close: "2026-04-01" },
      bear: { open: "2026-03-01", close: "2026-04-01" },
      moose: { open: "2026-03-01", close: "2026-06-01" },
    },
    licenseFees: { qualifyingLicense: 0, appFee: 50, pointFee: 100 },
    feeSchedule: [
      { name: "NR Combo License Application", amount: 50, frequency: "annual", required: true, notes: "Combo license application fee (covers elk + deer)." },
      { name: "NR Combo License", amount: 1051, frequency: "annual", required: true, notes: "Full combo license if drawn. Includes elk, deer, fishing, bird." },
      { name: "Preference Point (if not drawn)", amount: 100, frequency: "annual", required: false, notes: "Awarded automatically if unsuccessful. Cost is refunded application fee equivalent." },
    ],
    applicationApproach: "per_state",
    applicationApproachDescription: "Apply for a statewide combo license. If drawn, you get elk + deer tags. District selection happens after draw results.",
    applicationTips: [
      "The combo license is an all-in deal: one application for elk + deer. Great value if drawn.",
      "Special permits (moose, sheep, goat, bear) are separate applications with bonus points (squared).",
      "NR combo license quota is limited — apply every year to build preference points.",
      "B-tags (cow elk) are often available OTC after the draw for additional opportunity.",
    ],
    availableSpecies: ["elk", "mule_deer", "bear", "moose", "whitetail"],
    drawResultDates: { elk: "2026-06-15", mule_deer: "2026-06-15", bear: "2026-06-15", moose: "2026-07-01" },
    pointCost: { elk: 100, mule_deer: 100, bear: 50, moose: 50 },
    color: "#065F46",
    logistics: {
      primaryAirport: "BZN (Bozeman Yellowstone)",
      secondaryAirports: ["BIL (Billings)", "MSO (Missoula)", "GTF (Great Falls)"],
      rentalCarNotes: "4WD required for most hunting areas. BZN and BIL have best rental selection. Reserve early for October-November — rentals sell out during hunting season. Chains or good snow tires recommended for late season.",
      meatProcessing: "Processors throughout MT. Montana Meats (Bozeman), Yellowstone Meats (Billings). Most processors ship. Budget $200-350 for elk processing + shipping.",
      drivingNotes: "BZN to SW MT hunting: 1-2 hrs. BIL to eastern MT: 2-4 hrs. Montana is huge — plan your airport based on hunt area. MSO for western MT, GTF for Rocky Mountain Front.",
    },
    pointOnlyApplication: {
      instructions: "Apply for the NR Big Game Combo through FWP portal. If not drawn, you automatically receive a preference point. Application fee ($50) is your point investment.",
      purchaseUrl: "https://fwp.mt.gov/buyandapply",
      deadline: "April 1, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 2 - Oct 13", notes: "Long season. Elk bugling, backcountry access. Lower pressure than rifle.", bestFor: "backpack" },
      { tier: "General Rifle", dates: "Oct 22 - Nov 26", notes: "5+ week season. Opening week pressure, then thins out. Snow helps movement.", bestFor: "any" },
      { tier: "Whitetail Rut", dates: "Nov 10-25", notes: "Peak whitetail rut in river bottoms and coulees. Combo license includes a whitetail tag.", bestFor: "truck_camp" },
    ],
    statePersonality: "Montana is the best value in western hunting. One combo license gives you elk, deer, and whitetail — three hunts for the price of one. The preference point system means you'll draw every 2-3 years with discipline. Montana has massive public land, diverse terrain from prairie coulees to alpine basins, and the general season is 5+ weeks long. The catch: NR combo licenses are limited, so building preference points is essential. Spring bear is OTC and an excellent add-on trip. Montana rewards the persistent hunter who applies every year.",
  },
  {
    id: "NV",
    name: "Nevada",
    abbreviation: "NV",
    pointSystem: "bonus_squared",
    pointSystemDetails: {
      squared: true,
      description: "Bonus point system with squared weighting. (Points+1)^2 chances in draw.",
    },
    fgUrl: "https://www.ndow.org",
    buyPointsUrl: "https://www.ndow.org/hunt/apply-for-a-tag/",
    applicationDeadlines: {
      elk: { open: "2026-03-10", close: "2026-04-14" },
      mule_deer: { open: "2026-03-10", close: "2026-04-14" },
    },
    licenseFees: { qualifyingLicense: 142, appFee: 15, pointFee: 0 },
    feeSchedule: [
      { name: "Hunting License", amount: 142, frequency: "annual", required: true, notes: "Required before applying. Your license IS your point entry." },
      { name: "Application Fee", amount: 15, frequency: "per_species", required: true, notes: "Per species application fee." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit with up to 5 choices ranked. Bonus squared system rewards patience — your odds improve exponentially with points.",
    applicationTips: [
      "Your hunting license IS your point entry — buying the license alone earns a bonus point if you don't draw.",
      "Squared bonus means 5 points = 36 chances vs 1 chance for a zero-point applicant. Patience pays off big.",
      "List 5 choices per species — don't leave choices blank, it costs you nothing.",
      "Trophy quality is exceptional. Most NV hunts are once-in-a-lifetime experiences.",
    ],
    availableSpecies: ["elk", "mule_deer"],
    drawResultDates: { elk: "2026-06-01", mule_deer: "2026-06-01" },
    pointCost: { elk: 15, mule_deer: 15 },
    color: "#7C3AED",
    logistics: {
      primaryAirport: "RNO (Reno-Tahoe International)",
      secondaryAirports: ["LAS (Las Vegas)", "EKO (Elko)"],
      rentalCarNotes: "4WD strongly recommended. High-clearance SUV ideal for remote NV roads. RNO has best selection for northern units. LAS works for southern units. Carry extra water and fuel — services are sparse.",
      meatProcessing: "Limited processors in rural NV. Elko Custom Meats, Winnemucca Locker. Plan to quarter and ice the animal yourself and drive to a processor. Ship from Elko or Reno FedEx.",
      drivingNotes: "RNO to Jarbidge area: 4-5 hrs via I-80 E → Hwy 225 N. NV units require long drives on remote roads. Bring a spare tire and recovery gear. Cell service extremely limited.",
    },
    pointOnlyApplication: {
      instructions: "Buy your NV hunting license ($142) through NDOW portal. This alone earns you a bonus point. Add the $15 application fee per species to also enter the draw. Your license IS your point investment.",
      purchaseUrl: "https://www.ndow.org/hunt/apply-for-a-tag/",
      deadline: "April 14, 2026",
    },
    seasonTiers: [
      { tier: "Early Rifle", dates: "Sep 10-25", notes: "Warm weather, elk still in summer patterns. Higher elevations.", bestFor: "backpack" },
      { tier: "Late Rifle", dates: "Oct 10 - Nov 15", notes: "Cooler temps. Mule deer rut. Animals moving to winter range. Prime glassing conditions.", bestFor: "truck_camp" },
    ],
    statePersonality: "Nevada is your long-term trophy investment. The bonus-squared system means your odds improve exponentially — 5 points gives you 36x the chances of a first-time applicant. Nevada produces some of the largest mule deer and elk in the West, but tags are extremely limited. This is a patience play: invest $157/year (license + app fee) and let the math compound. When you finally draw, expect a hunt of a lifetime with near-trophy-class animals. NV is remote, harsh, and wild — exactly what makes it special.",
  },
  {
    id: "AZ",
    name: "Arizona",
    abbreviation: "AZ",
    pointSystem: "bonus",
    pointSystemDetails: {
      squared: false,
      description: "Bonus point system (not squared). Each point = 1 additional chance.",
    },
    fgUrl: "https://www.azgfd.com",
    buyPointsUrl: "https://www.azgfd.com/hunting/draw/",
    applicationDeadlines: {
      elk: { open: "2026-02-11", close: "2026-03-11" },
      mule_deer: { open: "2026-02-11", close: "2026-03-11" },
      bear: { open: "2026-06-03", close: "2026-07-08" },
    },
    licenseFees: { qualifyingLicense: 160, appFee: 15, pointFee: 0 },
    feeSchedule: [
      { name: "Hunting License", amount: 160, frequency: "annual", required: true, notes: "Required before applying. Also serves as your point entry." },
      { name: "Application Fee", amount: 15, frequency: "per_species", required: true, notes: "Per species application fee." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit with up to 5 choices. Bonus point system (not squared) — linear odds improvement.",
    applicationTips: [
      "License IS your point entry — buy even if not applying to earn a bonus point.",
      "AZ bonus points are NOT squared, so the advantage builds linearly. Less dramatic than NV.",
      "Elk quality is exceptional — AZ bulls average larger than most western states.",
      "Spring bear hunts are a separate draw with their own deadline.",
    ],
    availableSpecies: ["elk", "mule_deer", "bear"],
    drawResultDates: { elk: "2026-04-30", mule_deer: "2026-04-30", bear: "2026-08-01" },
    pointCost: { elk: 15, mule_deer: 15, bear: 15 },
    color: "#DC2626",
    logistics: {
      primaryAirport: "PHX (Phoenix Sky Harbor)",
      secondaryAirports: ["FLG (Flagstaff)", "TUS (Tucson)"],
      rentalCarNotes: "4WD helpful for forest roads but not always required. PHX has tons of rental options. FLG is closer to Kaibab and Rim Country units but limited rental selection. Roads are generally better maintained than other western states.",
      meatProcessing: "Flagstaff Meat Co, Payson Locker, Show Low Custom Meats. AZ has good processor coverage near hunting areas. Ship from FLG or PHX FedEx.",
      drivingNotes: "PHX to Kaibab (Unit 1): 4.5 hrs via I-17 N → I-40 W → Hwy 64. PHX to Rim Country: 2 hrs via Hwy 87. The drive from PHX to northern units is scenic but long.",
    },
    pointOnlyApplication: {
      instructions: "Buy your AZ hunting license ($160) through AZGFD portal. This earns a bonus point even if you don't apply. Add $15 app fee per species to also enter the draw.",
      purchaseUrl: "https://www.azgfd.com/hunting/draw/",
      deadline: "March 11, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 13 - Oct 2", notes: "Bull elk bugling in Rim Country. Warm days, cool nights. Pine forest hunting.", bestFor: "any" },
      { tier: "Early Rifle", dates: "Oct 17-22", notes: "Short season, high success in quality units. Animals still in early fall patterns.", bestFor: "any" },
      { tier: "Late Rifle", dates: "Nov 14-27", notes: "Rut season for elk. Cold mornings at elevation. Trophy bulls active.", bestFor: "truck_camp" },
      { tier: "Muzzleloader", dates: "Oct 3-16", notes: "Transition season. Good for patient hunters. Lower pressure.", bestFor: "any" },
    ],
    statePersonality: "Arizona is the sleeper trophy state. AZ bulls average larger body and antler size than nearly any other western state, and the limited tag allocation means low hunting pressure. The linear bonus point system is slower to compound than Nevada's squared system, but the hunt quality when you draw is exceptional. Kaibab (Unit 1) is legendary for both elk and mule deer. The Mogollon Rim offers accessible hunting with stunning scenery. AZ is worth the long-term point investment for the hunter who wants a genuine trophy experience.",
  },
  {
    id: "UT",
    name: "Utah",
    abbreviation: "UT",
    pointSystem: "dual",
    pointSystemDetails: {
      description: "Preference points for general season. Bonus points for limited-entry.",
    },
    fgUrl: "https://wildlife.utah.gov",
    buyPointsUrl: "https://wildlife.utah.gov/hunting-in-utah.html",
    applicationDeadlines: {
      elk: { open: "2026-01-30", close: "2026-03-05" },
      mule_deer: { open: "2026-01-30", close: "2026-03-05" },
      bear: { open: "2026-01-30", close: "2026-03-05" },
      moose: { open: "2026-01-30", close: "2026-03-05" },
    },
    licenseFees: { qualifyingLicense: 65, appFee: 10, pointFee: 0 },
    feeSchedule: [
      { name: "Hunting License", amount: 65, frequency: "annual", required: true, notes: "Required before applying." },
      { name: "Application Fee", amount: 10, frequency: "per_species", required: true, notes: "Per species application." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit. Preference points for general season; bonus points for limited-entry and once-in-a-lifetime species.",
    applicationTips: [
      "Utah has TWO point systems: preference for general, bonus for limited-entry/OIAL.",
      "Moose, goat, bison are once-in-a-lifetime — you can only draw one ever.",
      "General season elk is easier to draw but high pressure. Limited-entry units are the trophy play.",
      "Application period is early (Jan-Mar) — don't miss the window.",
    ],
    availableSpecies: ["elk", "mule_deer", "bear", "moose"],
    drawResultDates: { elk: "2026-05-15", mule_deer: "2026-05-15", bear: "2026-05-15", moose: "2026-05-15" },
    pointCost: { elk: 10, mule_deer: 10, bear: 10, moose: 10 },
    color: "#B45309",
    logistics: {
      primaryAirport: "SLC (Salt Lake City International)",
      secondaryAirports: ["SGU (St. George)", "CDC (Cedar City)"],
      rentalCarNotes: "4WD recommended for backcountry units. SLC has excellent rental options. Good roads for most general-season areas. Southern UT desert units may need high clearance.",
      meatProcessing: "Utah has good processor coverage. Heber Valley Meats, Spanish Fork Locker, Cedar City Custom Meats. Most offer shipping. Budget $150-250 for elk.",
      drivingNotes: "SLC is centrally located. 1-2 hrs to most Wasatch units. 3-4 hrs to southern UT limited-entry areas. I-15 corridor makes north-south travel easy.",
    },
    pointOnlyApplication: {
      instructions: "Apply through UT DWR portal. Select your species and choose 'preference point only' option. License ($65) + app fee ($10) = $75/year total. Bonus points for limited-entry build separately.",
      purchaseUrl: "https://wildlife.utah.gov/hunting-in-utah.html",
      deadline: "March 5, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Aug 17 - Sep 12", notes: "Earliest opener in the West. Elk bugling. Hot days, cool mornings. High elevation.", bestFor: "backpack" },
      { tier: "Muzzleloader", dates: "Sep 25 - Oct 3", notes: "Short season. Elk transitioning to fall patterns. Lower pressure.", bestFor: "any" },
      { tier: "Any Weapon (General)", dates: "Oct 7-15", notes: "General season any-bull. High pressure on public land. Get deep or hunt smart.", bestFor: "any" },
      { tier: "Limited Entry Rifle", dates: "Oct 7-20", notes: "Trophy units. Low tag numbers = low pressure. Premium experience.", bestFor: "any" },
    ],
    statePersonality: "Utah is a dual-track state. General season elk is accessible but competitive — high pressure on public land means you need to hike deeper than others or scout better. The real value is in limited-entry units where preference and bonus points create a clear path to trophy-quality hunts. The early archery opener (mid-August) is unique and gives you a head start on the season. SLC airport makes logistics easy, and the state's diverse terrain — from Wasatch alpine to southern desert canyons — offers something for every hunting style. The low application costs ($75/year) make UT an easy state to add to any portfolio.",
  },
  {
    id: "NM",
    name: "New Mexico",
    abbreviation: "NM",
    pointSystem: "random",
    pointSystemDetails: {
      description: "Pure random lottery. No point system. Equal odds every year.",
    },
    fgUrl: "https://www.wildlife.state.nm.us",
    buyPointsUrl: "https://www.wildlife.state.nm.us/hunting/",
    applicationDeadlines: {
      elk: { open: "2026-03-18", close: "2026-04-22" },
      mule_deer: { open: "2026-03-18", close: "2026-04-22" },
      bear: { open: "2026-03-18", close: "2026-04-22" },
    },
    licenseFees: { qualifyingLicense: 0, appFee: 12, pointFee: 0 },
    feeSchedule: [
      { name: "Application Fee", amount: 12, frequency: "per_species", required: true, notes: "Per species. No license required to apply." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit. Pure random lottery — no points, everyone has equal odds. Apply every year for a chance.",
    applicationTips: [
      "No points system — pure lottery. Apply every single year, it costs almost nothing.",
      "NM is the great equalizer. A first-time applicant has the same odds as a 10-year veteran.",
      "Some of the best elk hunting in the West. Quality units like 34 (Valles Caldera) are world-class.",
      "No qualifying license needed to apply — just the $12 app fee.",
    ],
    availableSpecies: ["elk", "mule_deer", "bear"],
    drawResultDates: { elk: "2026-06-15", mule_deer: "2026-06-15", bear: "2026-06-15" },
    pointCost: { elk: 0, mule_deer: 0, bear: 0 },
    color: "#EA580C",
    logistics: {
      primaryAirport: "ABQ (Albuquerque International Sunport)",
      secondaryAirports: ["SAF (Santa Fe)"],
      rentalCarNotes: "4WD helpful for mountain units but not always required. ABQ has full rental car selection. Roads in NM are generally better maintained than MT/WY backcountry. Carry water — it's desert country.",
      meatProcessing: "Santa Fe Custom Meats, Albuquerque processors, Raton Locker (northern NM). Ship from ABQ FedEx. Budget $150-200 for elk.",
      drivingNotes: "ABQ to northern NM elk country (Units 34, 6, 15): 2-3 hrs via I-25 N. ABQ to Gila area (southern): 3-4 hrs via I-25 S → Hwy 152. Central location makes most units accessible same day.",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 1-24", notes: "Bugling season in high country. Pine/aspen forests. Cool mornings.", bestFor: "backpack" },
      { tier: "Muzzleloader", dates: "Oct 1-9", notes: "Transition season. Elk less vocal but still patternable.", bestFor: "any" },
      { tier: "1st Rifle", dates: "Oct 15-19", notes: "5-day season. High success in quality units.", bestFor: "any" },
      { tier: "2nd Rifle", dates: "Nov 1-5", notes: "Elk moving to lower elevations. Good for truck-camp glassing.", bestFor: "truck_camp" },
      { tier: "3rd Rifle (Youth/Mobility)", dates: "Nov 22-26", notes: "Late season. Limited entry. Great for Thanksgiving trip hunts.", bestFor: "truck_camp" },
    ],
    statePersonality: "New Mexico is your wild card lottery ticket. No points, no waiting — just $12 and pure luck. Apply every single year because it costs almost nothing and the quality is world-class. Units like 34 (Valles Caldera) and 6 (Sangre de Cristos) produce bulls rivaling anywhere in the West. NM also has some of the earliest draw results, so if you draw here, you can adjust your other state plans accordingly. The terrain ranges from high desert to alpine meadows, and the Southwestern hunting culture is unique. NM is the ultimate bonus opportunity in any portfolio.",
  },
  {
    id: "OR",
    name: "Oregon",
    abbreviation: "OR",
    pointSystem: "hybrid",
    pointSystemDetails: {
      preferencePct: 75,
      randomPct: 25,
      description: "75% preference, 25% random draw for controlled hunts.",
    },
    fgUrl: "https://www.dfw.state.or.us",
    buyPointsUrl: "https://www.dfw.state.or.us/resources/hunting/",
    applicationDeadlines: {
      elk: { open: "2026-05-01", close: "2026-05-15" },
      mule_deer: { open: "2026-05-01", close: "2026-05-15" },
      bear: { open: "2026-05-01", close: "2026-05-15" },
    },
    licenseFees: { qualifyingLicense: 0, appFee: 8, pointFee: 0 },
    feeSchedule: [
      { name: "Application Fee", amount: 8, frequency: "per_species", required: true, notes: "Cheap application. No license required to apply." },
    ],
    applicationApproach: "per_unit",
    applicationApproachDescription: "Apply per unit for controlled hunts. 75/25 preference/random split. Some general season hunts are OTC.",
    applicationTips: [
      "One of the cheapest states to apply in — only $8/species. No excuse not to apply.",
      "General season Roosevelt elk hunts in western OR are often OTC (no draw needed).",
      "Eastern OR controlled hunts offer better trophy quality but require points.",
      "Late application deadline (May) gives you time to plan after other state results.",
    ],
    availableSpecies: ["elk", "mule_deer", "bear"],
    drawResultDates: { elk: "2026-07-01", mule_deer: "2026-07-01", bear: "2026-07-01" },
    pointCost: { elk: 8, mule_deer: 8, bear: 8 },
    color: "#16A34A",
    logistics: {
      primaryAirport: "PDX (Portland International)",
      secondaryAirports: ["RDM (Redmond/Bend)", "MFR (Medford)"],
      rentalCarNotes: "4WD recommended for eastern OR backcountry. PDX has full selection. RDM is closer to central OR hunting areas. Roads in western OR are generally good; eastern OR can be rough.",
      meatProcessing: "Bend Custom Meats, Prineville Locker, La Grande processors. Ship from RDM or PDX FedEx.",
      drivingNotes: "PDX to eastern OR (Starkey, Ochoco): 3-5 hrs via I-84 E or Hwy 26. RDM to central OR units: 1-2 hrs. Western OR Roosevelt elk areas: 1-2 hrs from PDX.",
    },
    pointOnlyApplication: {
      instructions: "Apply through ODFW portal. If you don't draw, you automatically receive a preference point for $8. No separate point-only purchase needed.",
      purchaseUrl: "https://www.dfw.state.or.us/resources/hunting/",
      deadline: "May 15, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Aug 27 - Sep 25", notes: "Early opener. Roosevelt elk in western OR, Rocky Mountain elk in eastern OR.", bestFor: "backpack" },
      { tier: "1st Rifle (Controlled)", dates: "Oct 1-7", notes: "Short controlled hunt. Premium experience in limited units.", bestFor: "any" },
      { tier: "2nd Rifle (General)", dates: "Oct 15-21", notes: "General season. Higher pressure but accessible. OTC in some areas.", bestFor: "any" },
      { tier: "Late Rifle", dates: "Nov 5-11", notes: "Late season. Deer rut. Migration patterns.", bestFor: "truck_camp" },
    ],
    statePersonality: "Oregon is the sleeper value play. At just $8/species, it's the cheapest state to apply in — there's no reason NOT to have OR in your portfolio. The 75/25 hybrid system builds points predictably for eastern OR controlled hunts, while western OR Roosevelt elk hunts are often OTC. The late application deadline (May) is strategically perfect — you'll know your draw results from CO, WY, and AZ before you even need to apply. Oregon rewards the patient hunter who builds points quietly while taking OTC opportunities in the meantime.",
  },
  {
    id: "ID",
    name: "Idaho",
    abbreviation: "ID",
    pointSystem: "random",
    pointSystemDetails: {
      description: "Pure random draw. No point system. Everyone has equal odds.",
    },
    fgUrl: "https://idfg.idaho.gov",
    buyPointsUrl: "https://idfg.idaho.gov/licenses",
    applicationDeadlines: {
      elk: { open: "2025-12-05", close: "2025-12-15" },
      mule_deer: { open: "2025-12-05", close: "2025-12-15" },
      bear: { open: "2026-04-01", close: "2026-04-30" },
      moose: { open: "2025-12-05", close: "2025-12-15" },
      whitetail: { open: "2025-12-05", close: "2025-12-15" },
    },
    licenseFees: { qualifyingLicense: 154.75, appFee: 0, pointFee: 0 },
    feeSchedule: [
      { name: "NR Hunting License", amount: 154.75, frequency: "annual", required: true, notes: "Required to apply. Also serves as your elk/deer tag for general zones." },
      { name: "Controlled Hunt Application", amount: 0, frequency: "per_species", required: false, notes: "No additional fee for controlled hunt applications." },
    ],
    applicationApproach: "per_state",
    applicationApproachDescription: "Zone-based system. General tags come with your license. Controlled hunts are per-unit draw with no points — pure random.",
    applicationTips: [
      "Your NR hunting license IS your general elk/deer tag for most zones. You can hunt general without drawing.",
      "Controlled hunts are pure random — no points, just luck. Apply every year.",
      "Idaho has some of the most diverse opportunities: elk, deer, bear, moose, whitetail, wolf.",
      "Super early deadline (December) — easiest one to miss. Set a calendar reminder.",
      "Spring bear is a separate application window in April.",
    ],
    availableSpecies: ["elk", "mule_deer", "bear", "moose", "whitetail"],
    drawResultDates: { elk: "2026-02-15", mule_deer: "2026-02-15", bear: "2026-06-01", moose: "2026-02-15", whitetail: "2026-02-15" },
    pointCost: { elk: 0, mule_deer: 0, bear: 0, moose: 0, whitetail: 0 },
    color: "#0891B2",
    logistics: {
      primaryAirport: "BOI (Boise Airport)",
      secondaryAirports: ["IDA (Idaho Falls)", "SUN (Sun Valley)", "LWS (Lewiston)"],
      rentalCarNotes: "4WD essential for Idaho backcountry. BOI has good rental selection. IDA works for eastern ID units. Reserve early — fall hunting season depletes 4WD inventory. Many roads are unimproved forest service trails.",
      meatProcessing: "Idaho processors in Boise, McCall, Salmon, and Idaho Falls. D&B Custom Meats (Boise), Salmon Valley Meats. Ship from BOI FedEx. Budget $200-300 for elk.",
      drivingNotes: "BOI to central ID (Frank Church area): 3-4 hrs. BOI to Sawtooth Zone: 2.5 hrs via Hwy 21. IDA to eastern units: 1-2 hrs. Idaho is remote — plan extra drive time.",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Aug 30 - Sep 30", notes: "Bugling season. Backcountry wilderness areas. Remote and wild.", bestFor: "backpack" },
      { tier: "General Rifle", dates: "Oct 10 - Nov 18", notes: "Long general season. Your NR license IS your tag for general zones. No draw needed.", bestFor: "any" },
      { tier: "Controlled Hunt", dates: "Varies by unit", notes: "Draw-only hunts for premium units. Random draw, no points needed.", bestFor: "any" },
      { tier: "Spring Bear", dates: "Apr 15 - Jun 30", notes: "Excellent spring bear spot-and-stalk. Separate application. Green hillside glassing.", bestFor: "truck_camp" },
    ],
    statePersonality: "Idaho is the Swiss Army knife of western hunting states. Your NR hunting license ($155) IS your general elk and deer tag — no draw needed for general zones. That means you can hunt Idaho every single year, guaranteed. Controlled hunts for premium units are pure random draw with no points, so apply every year for a bonus shot. Idaho also has the earliest application deadline (December!) — set a calendar alarm or you'll miss it. The state offers elk, mule deer, whitetail, moose, bear, and wolf across terrain ranging from alpine wilderness to rolling prairie. Spring bear is an excellent add-on trip.",
  },
  {
    id: "KS",
    name: "Kansas",
    abbreviation: "KS",
    pointSystem: "preference_nr",
    pointSystemDetails: {
      description: "Preference points for nonresident deer only.",
    },
    fgUrl: "https://ksoutdoors.com",
    buyPointsUrl: "https://ksoutdoors.com/Hunting/Big-Game-Hunting",
    applicationDeadlines: {
      mule_deer: { open: "2026-04-01", close: "2026-04-28" },
      whitetail: { open: "2026-04-01", close: "2026-04-28" },
    },
    licenseFees: { qualifyingLicense: 0, appFee: 27.50, pointFee: 0 },
    feeSchedule: [
      { name: "NR Deer Application", amount: 27.50, frequency: "per_species", required: true, notes: "Application fee per species. Preference points for NR only." },
    ],
    applicationApproach: "per_state",
    applicationApproachDescription: "Statewide NR deer draw with preference points. One of the best whitetail destinations in the country.",
    applicationTips: [
      "Kansas is the premier western whitetail destination for non-residents.",
      "Preference points mean patience pays — build points if you want a specific unit.",
      "Mule deer are available in western KS but limited. Whitetail is the main attraction.",
      "NR deer permit includes either-species in most units.",
    ],
    availableSpecies: ["mule_deer", "whitetail"],
    drawResultDates: { mule_deer: "2026-06-01", whitetail: "2026-06-01" },
    pointCost: { mule_deer: 27.50, whitetail: 27.50 },
    color: "#CA8A04",
    logistics: {
      primaryAirport: "MCI (Kansas City International)",
      secondaryAirports: ["ICT (Wichita)", "GCK (Garden City)"],
      rentalCarNotes: "2WD is fine for most KS hunting. MCI has full rental selection. Western KS mule deer areas accessible via GCK. Farm roads are well-maintained dirt.",
      meatProcessing: "Kansas processors are plentiful. Dodge City Custom Meats (western KS), multiple KC-area processors. Ship from MCI or GCK FedEx.",
      drivingNotes: "MCI to western KS mule deer: 5-6 hrs via I-70 W. MCI to central KS whitetail: 2-3 hrs. KS is flat — drives are easy and fast.",
    },
    pointOnlyApplication: {
      instructions: "Apply through KDWPT portal for NR deer permit. If not drawn, you automatically receive a preference point. $27.50 per species.",
      purchaseUrl: "https://ksoutdoors.com/Hunting/Big-Game-Hunting",
      deadline: "April 28, 2026",
    },
    seasonTiers: [
      { tier: "Archery", dates: "Sep 14 - Dec 31", notes: "Long archery season. Rut action mid-November. Best for whitetail.", bestFor: "any" },
      { tier: "Muzzleloader", dates: "Sep 14-28", notes: "Early season. Hot weather. Patterns from summer still hold.", bestFor: "any" },
      { tier: "Rifle (Regular)", dates: "Nov 29 - Dec 10", notes: "Short rifle season. Post-rut bucks still moving. Cold weather.", bestFor: "truck_camp" },
      { tier: "Pre-Rut Whitetail", dates: "Oct 15 - Nov 5", notes: "Bucks establishing scrapes and rub lines. Perfect time for stand hunting.", bestFor: "any" },
      { tier: "Peak Rut Whitetail", dates: "Nov 5-20", notes: "Peak rut. Bucks on their feet all day. Best chance at a giant.", bestFor: "any" },
    ],
    statePersonality: "Kansas is the whitetail wildcard in your western portfolio. While everyone else is chasing elk in the mountains, KS produces some of the biggest whitetail bucks in North America. The NR preference point system makes it predictable — build 1-2 points and you're drawing. November rut hunts in the eastern KS river bottoms are legendary. Western KS also offers mule deer on agricultural land. At $27.50/year, it's a cheap addition that diversifies your portfolio beyond mountain hunts. Perfect for a Thanksgiving-week hunt trip.",
  },
];

export const STATES_MAP = Object.fromEntries(STATES.map((s) => [s.id, s]));

export function getStateById(id: string): State | undefined {
  return STATES_MAP[id];
}
